import type { Festival } from "@/lib/festivals";

// Source: edmmaniac.com, stagehoppers.com, edm.com lineup announcements (via search summaries).
export const breakaway2026 = {
  id: "breakaway-philadelphia-2026",
  name: "Breakaway Philadelphia",
  year: 2026,
  startDate: "2026-09-11",
  location: "Subaru Park, PA",
  dates: "Sep 11–12",
  gradient: "from-sky-400 via-indigo-500 to-fuchsia-600",
  partial: true,
  lineup: [
    "Tiësto",
    "Marshmello",
    "ISOxo",
    "SOFI TUKKER",
    "Malaa (Alter Ego)",
    "Whethan",
    "Layton Giordani",
    "Deathpact",
    "Swimming Paul",
    "2ŁØT",
    "ARMNHMR",
    "Avello",
    "Brainrack",
    "Capochino",
    "CID",
    "Devault",
    "Gazza",
    "HILLS",
    "JULS",
    "Klo",
    "KREAM",
    "Machaki",
    "Rich Dietz",
    "RLPZ",
    "STARJUNK 95",
    "Tavatli",
  ],
} satisfies Festival;
