import type { Festival } from "@/lib/festivals";

// Source: search summaries of rollingstone.com, thefader.com, tempo.co, electronicgroove.com,
// hollywoodreporter.com, variety.com (pages couldn't be fetched). ~130 of ~150 artists.
export const coachella2026 = {
  id: "coachella-2026",
  name: "Coachella",
  year: 2026,
  startDate: "2026-04-10",
  location: "Indio, CA",
  dates: "Apr 10–12 & 17–19",
  gradient: "from-orange-400 via-pink-500 to-purple-600",
  partial: true,
  lineup: [
    "Sabrina Carpenter",
    "Justin Bieber",
    "Karol G",
    "Anyma",
    "The xx",
    "The Strokes",
    "Young Thug",
    "Disclosure",
    "Turnstile",
    "GIVĒON",
    "Kaskade",
    "BIGBANG",
    "Addison Rae",
    "Laufey",
    "Major Lazer",
    "Ethel Cain",
    "Iggy Pop",
    "FKA twigs",
    "David Byrne",
    "Nine Inch Noize",
    "Labrinth",
    "sombr",
    "Interpol",
    "Jack White",
    "Dijon",
    "Teddy Swims",
    "KATSEYE",
    "Devo",
    "Sexyy Red",
    "Central Cee",
    "Foster the People",
    "Wet Leg",
    "Clipse",
    "PinkPantheress",
    "Alex G",
    "Solomun",
    "Swae Lee",
    "Taemin",
    "Royel Otis",
    "REZZ",
    "Fujii Kaze",
    "Adriatique",
    "Davido",
    "Boys Noize",
    "Geese",
    "Subtronics",
    "Little Simz",
    "Mochakk",
    "Duke Dumont",
    "Worship",
    "Armin van Buuren",
    "Adam Beyer",
    "Holly Humberstone",
    "Gigi Perez",
    "The Rapture",
    "Suicidal Tendencies",
    "Levity",
    "Blood Orange",
    "Moby",
    "Marlon Hoffstadt",
    "Lykke Li",
    "fakemink",
    "Gordo",
    "Creepy Nuts",
    "Joyce Manor",
    "BINI",
    "KETTAMA",
    "Groove Armada",
    "Joost",
    "HUGEL",
    "CMAT",
    "Slayyyter",
    "Prospa",
    "Hot Mulligan",
    "Hamdi",
    "Fleshwater",
    "Max Styler",
    "Wednesday",
    "Dabeull",
    "The Two Lips",
    "Ninajirachi",
    "Max Dean x Luke Dean",
    "Cachirula & Loojan",
    "Jessica Brankka",
    "Chloé Caillet",
    "rusowsky",
    "¥ØU$UK€ ¥UK1MAT$U",
    "Green Velvet x Ayybo",
    "Luísa Sonza",
    "ZULAN",
    "Los Hermanos Flores",
    "Bedouin",
    "Ceremony",
    "54 Ultra",
    "Noga Erez",
    "Ben Sterling",
    "Blondshell",
    "Lambrini Girls",
    "Ecca Vandal",
    "Mind Enterprises",
    "Freak Slug",
    "SOSA",
    "Mahmut Orhan",
    "Riordan",
    "Die Spitz",
    "Jaqck Glam",
    "BUNT.",
    "French Police",
    "Black Fag",
    "Oklou",
    "Röyksopp",
    "The Chats",
    "DRAIN",
    "Model/Actriz",
    "COBRAN",
    "Los Retros",
    "WhoMadeWho",
    "Jane Remover",
    "RBZ",
    "Glitterer",
    "Carlita",
    "Josh Baker",
    "MËSTIZA",
    "&friends",
    "AZZECCA",
    "LE YORA",
    "Samia",
    "Tomora",
  ],
} satisfies Festival;
