import type { Festival } from "@/lib/festivals";

const GRADIENT = "from-orange-400 via-pink-500 to-purple-600";

// 2022–2025 source: search summaries of thefader.com livestream schedules, billboard.com,
// brooklynvegan.com, consequence.net, timeout.com (pages couldn't be fetched).

// Ye withdrew (Swedish House Mafia & The Weeknd replaced him), so he isn't listed.
export const coachella2022 = {
  id: "coachella-2022",
  name: "Coachella",
  year: 2022,
  startDate: "2022-04-15",
  location: "Indio, CA",
  dates: "Apr 15–17 & 22–24",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Harry Styles",
    "Billie Eilish",
    "Swedish House Mafia & The Weeknd",
    "Megan Thee Stallion",
    "Doja Cat",
    "Lil Baby",
    "Daniel Caesar",
    "Phoebe Bridgers",
    "Arcade Fire",
    "Karol G",
    "Flume",
    "Disclosure",
    "21 Savage",
    "Stromae",
    "Danny Elfman",
    "Run the Jewels",
    "Jamie xx",
    "Big Sean",
    "Grupo Firme",
    "Louis The Child",
    "Baby Keem",
    "Still Woozy",
    "King Gizzard & The Lizard Wizard",
    "Snoh Aalegra",
    "City Girls",
    "Madeon",
    "NIKI",
    "Lane 8",
    "slowthai",
    "IDLES",
    "Princess Nokia",
    "Bishop Briggs",
    "Ari Lennox",
    "Carly Rae Jepsen",
    "Anitta",
    "The Hu",
    "Raveena",
    "Mika",
    "Omar Apollo",
    "Koffee",
    "Masego",
    "Wallows",
    "Cuco",
    "88rising's Head in the Clouds Forever",
    "Beach Bunny",
    "JID",
    "Giveon",
    "100 gecs",
    "Caroline Polachek",
    "BROCKHAMPTON",
    "Rich Brian",
    "Chelsea Cutler",
    "Current Joys",
    "Emo Nite",
    "Japanese Breakfast",
    "girl in red",
    "Rina Sawayama",
    "Steve Lacy",
    "Pabllo Vittar",
    "Isaiah Rashad",
    "Caribou",
    "Surf Curse",
    "Alec Benjamin",
    "Vince Staples",
    "FINNEAS",
    "Maggie Rogers",
    "Yola",
    "Banda MS",
    "beabadoobee",
    "Orville Peck",
    "Chicano Batman",
    "Dave",
    "Joji",
    "Emotional Oranges",
    "Channel Tres",
    "Kim Petras",
    "Fred again..",
    "Duck Sauce",
    "Ali Gatie",
    "Duke Dumont",
    "Jessie Reyez",
    "Denzel Curry",
    "Belly",
  ],
} satisfies Festival;

// Frank Ocean played Weekend 1 only. Skrillex, Four Tet & Fred again.. closed Weekend 2 as a surprise.
export const coachella2023 = {
  id: "coachella-2023",
  name: "Coachella",
  year: 2023,
  startDate: "2023-04-14",
  location: "Indio, CA",
  dates: "Apr 14–16 & 21–23",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Bad Bunny",
    "BLACKPINK",
    "Frank Ocean",
    "Calvin Harris",
    "blink-182",
    "Björk",
    "Rosalía",
    "Gorillaz",
    "Kali Uchis",
    "Porter Robinson",
    "Skrillex",
    "Four Tet",
    "Fred again..",
    "Burna Boy",
    "The Chemical Brothers",
    "Kaytranada",
    "Blondie",
    "Becky G",
    "Metro Boomin",
    "$uicideboy$",
    "Labrinth",
    "Charli XCX",
    "boygenius",
    "Underworld",
    "Eric Prydz presents HOLO",
    "FISHER + Chris Lake",
    "A Boogie Wit da Hoodie",
    "Dominic Fike",
    "Jai Paul",
    "Jackson Wang",
    "Latto",
    "The Blaze",
    "WILLOW",
    "GloRilla",
    "Jai Wolf",
    "Boris Brejcha",
    "2manydjs",
    "Christine and the Queens",
    "Rae Sremmurd",
    "Weyes Blood",
    "Alex G",
    "DPR LIVE + DPR IAN",
    "Stick Figure",
    "Adam Beyer",
    "Big Wild",
    "MK",
    "Cannons",
    "Romy",
    "Gordo",
    "Fousheé",
    "Noname",
    "Pi'erre Bourne",
    "Cassian",
    "Joy Crookes",
    "TSHA",
    "El Michels Affair",
    "Paris Texas",
    "LP Giobbi",
    "Momma",
    "Ali Sethi",
    "Minus the Light",
    "Los Bitchos",
    "Conexión Divina",
    "Airrica",
    "FKJ",
    "Pusha T",
    "Tobe Nwigwe",
    "Wet Leg",
    "SG Lewis",
    "Yves Tumor",
    "The Garden",
    "TESTPILOT",
    "Angèle",
    "MUNA",
    "Maceo Plex",
    "Two Friends",
    "YUNGBLUD",
    "Jamie Jones",
    "Ashnikko",
    "Malaa",
    "TV Girl",
    "Whyte Fang",
    "Doechii",
    "BENEE",
    "Idris Elba",
    "Magdalena Bay",
    "Vintage Culture",
    "Domi & JD Beck",
    "Dombresky",
    "DannyLux",
    "Nora En Pure",
    "Overmono",
    "Uncle Waffles",
    "¿Téo?",
    "Mochakk",
    "Gabriels",
    "Saba",
    "Dennis Cruz",
    "PAWSA",
    "Soul Glo",
    "Lava La Rue",
    "Sleaford Mods",
    "The Comet Is Coming",
    "Oliver Koletzki",
    "Kyle Watson",
    "The Murder Capital",
    "Chris Stussy",
    "Jupiter & Okwess",
    "070 Shake",
    "AG Club",
    "Bakar",
    "Bratty",
    "Chloé Caillet",
    "Chromeo",
    "Colyn",
    "DJ Tennis + Carlita",
    "DRAMA",
    "Destroy Boys",
    "Diljit Dosanjh",
    "Dinner Party",
    "Donavan's Yard",
    "EARTHGANG",
    "Eladio Carrión",
    "Elderbrook",
    "Elyanna",
    "Ethel Cain",
    "Flo Milli",
    "Francis Mercier",
    "Hiatus Kaiyote",
    "Horsegirl",
    "Hot Since 82",
    "Jan Blomqvist",
    "Keinemusik",
    "Kenny Beats",
    "Los Fabulosos Cadillacs",
    "Marc Rebillet",
    "Methame",
    "Monolink",
    "Mura Masa",
    "Nia Archives",
    "Rebelution",
    "Remi Wolf",
    "SOFI TUKKER",
    "Scowl",
    "Shenseea",
    "Snail Mail",
    "Sunset Rollercoaster",
    "Tale Of Us",
    "The Breeders",
    "The Kid LAROI",
    "The Linda Lindas",
    "UMI",
    "WhoMadeWho",
    "Yaeji",
    "Yung Lean",
  ],
} satisfies Festival;

// Vampire Weekend played Weekend 1 only. Everything Always = Dom Dolla & John Summit.
export const coachella2024 = {
  id: "coachella-2024",
  name: "Coachella",
  year: 2024,
  startDate: "2024-04-12",
  location: "Indio, CA",
  dates: "Apr 12–14 & 19–21",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Lana Del Rey",
    "Tyler, The Creator",
    "Doja Cat",
    "No Doubt",
    "Peso Pluma",
    "Lil Uzi Vert",
    "Justice",
    "BZRP",
    "Deftones",
    "ATEEZ",
    "Everything Always",
    "Peggy Gou",
    "Young Miko",
    "Sabrina Carpenter",
    "Anti Up",
    "Steve Angello",
    "Blur",
    "Ice Spice",
    "Gesaffelstein",
    "Sublime",
    "Jungle",
    "Dom Dolla",
    "Bleachers",
    "Grimes",
    "Jon Batiste",
    "LE SSERAFIM",
    "Orbital",
    "The Blessed Madonna",
    "Michael Bibi",
    "Vampire Weekend",
    "Taking Back Sunday",
    "Suki Waterhouse",
    "J Balvin",
    "Jhené Aiko",
    "Khruangbin",
    "Carin León",
    "John Summit",
    "Lil Yachty",
    "DJ Snake",
    "LUDMILLA",
    "The Rose",
    "Anyma",
    "ARTBAT",
    "Carlita",
    "BICEP",
    "Victoria Monét",
    "Reneé Rapp",
    "Tyla",
    "Chappell Roan",
    "Faye Webster",
    "Brittany Howard",
    "Oneohtrix Point Never",
    "Kevin Abstract",
    "The Last Dinner Party",
    "Black Country, New Road",
    "Mdou Moctar",
    "Feeble Little Horse",
  ],
} satisfies Festival;

// FKA twigs, Anitta and Gel cancelled; Weezer (W1) and Ed Sheeran (W2) were late additions.
export const coachella2025 = {
  id: "coachella-2025",
  name: "Coachella",
  year: 2025,
  startDate: "2025-04-11",
  location: "Indio, CA",
  dates: "Apr 11–13 & 18–20",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Lady Gaga",
    "Green Day",
    "Travis Scott",
    "Post Malone",
    "Missy Elliott",
    "Charli xcx",
    "Megan Thee Stallion",
    "JENNIE",
    "LISA",
    "Zedd",
    "Benson Boone",
    "MARINA",
    "The Marías",
    "Tyla",
    "The Go-Go's",
    "Thee Sacred Souls",
    "Seun Kuti & Egypt 80",
    "Gabe Real",
    "SPEED",
    "Los Mirlos",
    "Kneecap",
    "julie",
    "Eyedress",
    "Miike Snow",
    "SAINt JHN",
    "Lola Young",
    "Djo",
    "d4vd",
    "A. G. Cook",
    "Artemas",
    "CA7RIEL & Paco Amoroso",
    "Indo Warehouse",
    "The Prodigy",
    "Yeat",
    "GloRilla",
    "Mustard",
    "Vintage Culture",
    "Chris Stussy",
    "Pete Tong b2b Ahmed Spins",
    "Tinlicker",
    "Polo & Pan",
    "Clairo",
    "ENHYPEN",
    "Jimmy Eat World",
    "T-Pain",
    "Misfits",
    "Beth Gibbons",
    "Weezer",
    "Ed Sheeran",
    "Japanese Breakfast",
    "2hollis",
    "Parcels",
    "Keinemusik",
    "Above & Beyond",
    "Eli Brown",
    "Disco Lines",
    "Amelie Lens",
    "Alok",
    "The Dare",
    "Mind Against x Massano",
    "Infected Mushroom",
    "DJ Gigola",
    "Talón",
    "Shoreline Mafia",
    "salute",
    "Mau P",
    "Glass Beams",
    "Viagra Boys",
    "Medium Build",
    "DARKSIDE",
    "Junior H",
    "Shaboozey",
    "Kraftwerk",
    "Muni Long",
    "Tripolism",
    "Ty Dolla $ign",
    "Circle Jerks",
    "Basement Jaxx",
    "Still Woozy",
    "beabadoobee",
    "Jaqck Glam",
    "Ginger Root",
    "Snow Strippers",
    "Amyl and the Sniffers",
    "Arca",
    "Rema",
    "Jessie Murph",
    "Mohamed Ramadan",
    "BigXthaPlug",
    "SOFT PLAY",
    "Amaarae",
    "The Beaches",
    "Hope Tala",
    "Wisp",
    "MEUTE",
    "Bob Vylan",
    "Kumo 99",
    "Salado",
    "KsoFresco",
    "Fcukers",
    "Canyon Cody",
    "Interplanetary Criminal",
    "AMÉMÉ",
    "Yulia Niko",
    "Ivan Cornejo",
  ],
} satisfies Festival;

// Source: search summaries of rollingstone.com, thefader.com, tempo.co, electronicgroove.com,
// hollywoodreporter.com, variety.com (pages couldn't be fetched). ~130 of ~150 artists.
export const coachella2026 = {
  id: "coachella-2026",
  name: "Coachella",
  year: 2026,
  startDate: "2026-04-10",
  location: "Indio, CA",
  dates: "Apr 10–12 & 17–19",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Sabrina Carpenter",
    "Justin Bieber",
    "Karol G",
    "Anyma",
    "The xx",
    "The Strokes",
    "Young Thug",
    "Disclosure",
    "Turnstile",
    "GIVĒON",
    "Kaskade",
    "BIGBANG",
    "Addison Rae",
    "Laufey",
    "Major Lazer",
    "Ethel Cain",
    "Iggy Pop",
    "FKA twigs",
    "David Byrne",
    "Nine Inch Noize",
    "Labrinth",
    "sombr",
    "Interpol",
    "Jack White",
    "Dijon",
    "Teddy Swims",
    "KATSEYE",
    "Devo",
    "Sexyy Red",
    "Central Cee",
    "Foster the People",
    "Wet Leg",
    "Clipse",
    "PinkPantheress",
    "Alex G",
    "Solomun",
    "Swae Lee",
    "Taemin",
    "Royel Otis",
    "REZZ",
    "Fujii Kaze",
    "Adriatique",
    "Davido",
    "Boys Noize",
    "Geese",
    "Subtronics",
    "Little Simz",
    "Mochakk",
    "Duke Dumont",
    "Worship",
    "Armin van Buuren",
    "Adam Beyer",
    "Holly Humberstone",
    "Gigi Perez",
    "The Rapture",
    "Suicidal Tendencies",
    "Levity",
    "Blood Orange",
    "Moby",
    "Marlon Hoffstadt",
    "Lykke Li",
    "fakemink",
    "Gordo",
    "Creepy Nuts",
    "Joyce Manor",
    "BINI",
    "KETTAMA",
    "Groove Armada",
    "Joost",
    "HUGEL",
    "CMAT",
    "Slayyyter",
    "Prospa",
    "Hot Mulligan",
    "Hamdi",
    "Fleshwater",
    "Max Styler",
    "Wednesday",
    "Dabeull",
    "The Two Lips",
    "Ninajirachi",
    "Max Dean x Luke Dean",
    "Cachirula & Loojan",
    "Jessica Brankka",
    "Chloé Caillet",
    "rusowsky",
    "¥ØU$UK€ ¥UK1MAT$U",
    "Green Velvet x Ayybo",
    "Luísa Sonza",
    "ZULAN",
    "Los Hermanos Flores",
    "Bedouin",
    "Ceremony",
    "54 Ultra",
    "Noga Erez",
    "Ben Sterling",
    "Blondshell",
    "Lambrini Girls",
    "Ecca Vandal",
    "Mind Enterprises",
    "Freak Slug",
    "SOSA",
    "Mahmut Orhan",
    "Riordan",
    "Die Spitz",
    "Jaqck Glam",
    "BUNT.",
    "French Police",
    "Black Fag",
    "Oklou",
    "Röyksopp",
    "The Chats",
    "DRAIN",
    "Model/Actriz",
    "COBRAN",
    "Los Retros",
    "WhoMadeWho",
    "Jane Remover",
    "RBZ",
    "Glitterer",
    "Carlita",
    "Josh Baker",
    "MËSTIZA",
    "&friends",
    "AZZECCA",
    "LE YORA",
    "Samia",
    "Tomora",
  ],
} satisfies Festival;
