import type { Festival } from "@/lib/festivals";

// Creamfields (North), Daresbury, Cheshire. Requested via festival_requests.
// Source: search summaries of jambase.com day-by-day listings, checked against 1001tracklists set pages;
// weraveyou.com, nme.com (pages couldn't be fetched). All four days, all stages; a few smaller-tent acts may be
// missing. Some billed international acts may not have played due to 2021 travel restrictions (Nicky Romero,
// NERVO and Netsky were late additions as replacements).
export const creamfields2021 = {
  id: "creamfields-2021",
  name: "Creamfields",
  aliases: ["Creamfields North", "Creamfields UK"],
  year: 2021,
  startDate: "2021-08-26",
  location: "Daresbury, UK",
  dates: "Aug 26–29",
  gradient: "from-sky-400 via-indigo-500 to-fuchsia-600",
  partial: true,
  lineup: [
    "David Guetta",
    "The Chemical Brothers",
    "Martin Garrix",
    "Tiësto",
    "deadmau5",
    "Eric Prydz",
    "Carl Cox",
    "Armin van Buuren",
    "Above & Beyond",
    "Dimitri Vegas & Like Mike",
    "FISHER",
    "AFROJACK",
    "Alesso",
    "Faithless",
    "Basement Jaxx",
    "Pendulum",
    "Chase & Status",
    "CamelPhat",
    "Bicep",
    "Nina Kraviz",
    "Charlotte de Witte",
    "Peggy Gou",
    "Sven Väth",
    "Jamie Jones",
    "Andy C",
    "Oliver Heldens",
    "Jonas Blue",
    "Jax Jones",
    "Example",
    "Sigma",
    "Paul van Dyk",
    "Ferry Corsten",
    "Aly & Fila",
    "Nicky Romero",
    "NERVO",
    "Netsky",
    "Adam Beyer",
    "Kölsch",
    "Patrick Topping",
    "Solardo",
    "ARTBAT",
    "Tchami",
    "MK",
    "Paul Woolford",
    "Yousef",
    "Hot Since 82",
    "Claptone",
    "Gorgon City",
    "Pete Tong",
    "Loco Dice",
    "Marco Carola",
    "Joseph Capriati",
    "Nic Fanciulli",
    "Josh Wink",
    "Guti",
    "Benny Benassi",
    "Laidback Luke",
    "W&W",
    "Vini Vici",
    "Alok",
    "Topic",
    "Jodie Harsh",
    "Sam Divine",
    "Riva Starr",
    "Bassjackers",
    "Adaro",
    "La Fleur",
    "Franky Wah",
    "Low Steppa",
    "Eli Brown",
    "Hannah Wants",
    "Timmy Trumpet",
    "Will Sparks",
    "Sub Zero Project",
    "Scooter",
    "Brennan Heart",
    "Headhunterz",
    "Wildstylez",
    "Sound Rush",
    "Zatox",
    "Miss K8",
    "Kutski",
    "Ben Nicky",
    "Darren Styles",
    "Helena Hauff",
    "Dax J",
    "Leon Vynehall",
    "Richy Ahmed",
    "Dimension",
    "Voltage",
    "Bladerunner",
    "Randall",
    "S.P.Y",
    "Harriet Jaxxon",
    "Skantia",
    "Bou",
    "Tonn Piper",
    "GQ",
    "IC3",
    "Evil B",
    "Haribo",
    "Cristoph",
    "Majestic",
    "Jay Robinson",
    "SHOSH",
    "Local",
    "Livsey",
    "Beyond Chicago",
    "ANNA",
    "Disciples",
    "KC Lights",
    "MORTEN",
    "KREAM",
    "Bart B More",
    "Loopers",
    "Silque",
    "SOSA",
    "My Nu Leng",
    "Matrix & Futurebound",
    "Rhymster",
    "Leftwing : Kody",
    "OFFAIAH",
    "Nightlapse",
    "Alan Fitzpatrick",
    "Rebūke",
    "James Organ",
    "Denis Sulta",
    "Michael Bibi",
    "Mason Collective",
    "Simon Dunmore",
    "Todd Terry",
    "The Shapeshifters",
    "Teni Tinks",
    "Melvo Baptiste",
    "John O'Callaghan",
    "Menno de Jong",
    "Shugz",
    "David Rust",
    "Factor B",
    "Rob Harnetty",
    "Sefa",
    "Alex Kidd",
    "Minus the Crown",
    "Shaun T",
    "Phil Mackintosh",
    "Argy",
    "Bryan Kearney",
    "Craig Connelly",
    "Giuseppe Ottaviani",
    "Will Atkinson",
    "Chuckie",
    "Sick Individuals",
    "Thomas Gold",
    "Kryder",
    "Tom Staar",
    "Deniz Koyu",
    "D.O.D",
    "Magnificence",
    "Eden Prince",
    "Redfield",
    "M.I.K.E. Push",
    "Scot Project",
    "Signum",
    "Ben Gold",
    "Jase Thirlwall",
    "Ashley Smith",
    "DJ S.K.T",
    "Danny T",
    "Shaun Dean",
    "Jamie Duggan",
    "Shift K3Y",
    "Matt Thiss",
    "Juicy M",
    "Corey James",
    "Next Generation Noise",
  ],
} satisfies Festival;
