import type { Festival } from "@/lib/festivals";

// Source: search summaries of edm.com, edmidentity.com, djmag.com, press.insomniac.com,
// lasvegassun.com, weraveyou.com (pages couldn't be fetched). ~125 of ~247 artists.
export const edc2026 = {
  id: "edc-las-vegas-2026",
  name: "EDC Las Vegas",
  year: 2026,
  startDate: "2026-05-15",
  location: "Las Vegas, NV",
  dates: "May 15–17",
  gradient: "from-yellow-300 via-pink-500 to-fuchsia-600",
  partial: true,
  lineup: [
    "Martin Garrix",
    "Tiësto",
    "Zedd",
    "The Chainsmokers",
    "Kaskade",
    "John Summit",
    "FISHER",
    "Charlotte de Witte",
    "Armin van Buuren",
    "Above & Beyond",
    "Steve Aoki",
    "Porter Robinson",
    "Subtronics",
    "Chris Lake",
    "The Prodigy",
    "Underworld",
    "Alison Wonderland",
    "Seven Lions",
    "GRiZ b2b Wooli",
    "Paul van Dyk",
    "Peggy Gou",
    "Sub Focus",
    "Adventure Club",
    "Pegassi",
    "Darude",
    "San Holo",
    "Gareth Emery",
    "Paul Oakenfold",
    "Eli & Fur",
    "Tinlicker",
    "Ilan Bluestone",
    "Sarah de Warren",
    "Innellea",
    "MPH",
    "San Pacho",
    "Interplanetary Criminal",
    "MALUGI",
    "Snow Strippers",
    "Hannah Laing",
    "Chris Stussy",
    "Levity",
    "Lilly Palmer",
    "Beltran",
    "Nico Moreno",
    "KETTAMA",
    "Joseph Capriati",
    "Eli Brown",
    "Indira Paganotto",
    "Klangkuenstler",
    "Prospa",
    "Frankie Bones",
    "KI/KI",
    "Holy Priest",
    "Restricted",
    "Sub Zero Project",
    "Lil Texas",
    "Kuko b2b Johannes Schuster",
    "GRAVEDGR",
    "Robe Gee b2b Lenny Dee",
    "Lady Faith b2b LNY TNZ",
    "Audiofreq b2b Code Black b2b Toneshifterz",
    "Noizu",
    "OMNOM",
    "Wax Motif",
    "BOLO",
    "Luuk van Dijk",
    "Luke Dean",
    "Josh Baker",
    "Max Dean b2b Luke Dean",
    "Abana b2b Juliet Mendoza",
    "Sidney Charles b2b Bushbaby",
    "Chris Lorenzo b2b Bullet Tooth",
    "DJ Tennis b2b Red Axes",
    "MCR-T",
    "Paramida",
    "SALUTE b2b Chloé Caillet",
    "BAUGRUPPE90",
    "Heidi Lawden b2b Masha Mar",
    "HAAi b2b Luke Alessi",
    "ÆON:MODE",
    "ATLiens",
    "AHEE b2b Liquid Stranger",
    "INFEKT b2b Samplifire",
    "Avello b2b Dennett",
    "Boogie T b2b Distinct Motive",
    "Culture Shock",
    "Delta Heavy",
    "EAZYBAKED",
    "Eptic b2b Space Laces",
    "Fallen with MC Dino",
    "GHENGAR",
    "Getter",
    "GorillaT",
    "HEYZ",
    "HOL!",
    "Hybrid Minds",
    "Kai Wachi",
    "Muzz",
    "Mary Droppinz",
    "Nightstalker with MC Dino",
    "Viperactive",
    "Whethan",
    "Wooli",
    "YDG",
    "Doctor P b3b Flux Pavilion b3b FuntCase",
    "Josh Baker b3b KETTAMA b3b Prospa",
    "Walker & Royce b2b VNSSA",
    "Laidback Luke b2b Chuckie",
    "Beltran b2b Simas",
  ],
} satisfies Festival;

// Source: search summaries of lasvegas.edc.com, edmidentity.com, djmag.com, jambase.com set times
// and stage lists (pages couldn't be fetched). 9 main stages near-complete; art cars not included.
export const edc2025 = {
  id: "edc-las-vegas-2025",
  name: "EDC Las Vegas",
  year: 2025,
  startDate: "2025-05-16",
  location: "Las Vegas, NV",
  dates: "May 16–18",
  gradient: "from-yellow-300 via-pink-500 to-fuchsia-600",
  partial: true,
  lineup: [
    "Tiësto",
    "Martin Garrix",
    "Armin van Buuren",
    "Eric Prydz",
    "Kaskade",
    "Alesso",
    "Dom Dolla",
    "DJ Snake",
    "FISHER",
    "ILLENIUM b2b SLANDER",
    "AFROJACK",
    "Charlotte de Witte",
    "Excision",
    "REZZ",
    "Gesaffelstein",
    "Alison Wonderland b2b Kaskade",
    "RL Grime",
    "Chase & Status",
    "Sara Landry",
    "Amelie Lens",
    "Gorgon City",
    "Meduza",
    "James Hype",
    "Marlon Hoffstadt",
    "Mau P",
    "Mochakk",
    "Pryda",
    "Vini Vici",
    "Bicep presents Chroma",
    "Boys Noize",
    "TOKiMONSTA",
    "Andy C",
    "Skepta Más Tiempo",
    "Vintage Culture",
    "The Martinez Brothers b2b Loco Dice",
    "ARTBAT b2b MORTEN",
    "SLANDER b2b NGHTMRE",
    "Nora En Pure",
    "Alok",
    "Deorro & Friends",
    "Mike Posner",
    "Danny Avila",
    "Ben Nicky",
    "Dimension",
    "Xandra",
    "Noizu",
    "Lavern",
    "SVDDEN DEATH",
    "Sullivan King",
    "Liquid Stranger",
    "Levity",
    "Netsky",
    "Apashe",
    "Ray Volpe",
    "Riot Ten",
    "Caspa b2b Rusko",
    "Crankdat b2b Tape B",
    "Basstripper b2b Sota",
    "Jessica Audiffred b2b LAYZ",
    "RZRKT b2b Vastive",
    "AHEE",
    "Andromedik",
    "Distinct Motive",
    "DRINKURWATER",
    "Fury with MC Dino",
    "INFEKT",
    "INZO",
    "Kompany",
    "Level Up",
    "Of The Trees",
    "Rudim3ntal",
    "Samplifire",
    "Shades",
    "Simula",
    "Soothslayer",
    "Steller",
    "Truth",
    "YDG",
    "Armand Van Helden",
    "Tchami x Malaa: No Redemption",
    "I Hate Models presents Face II Face A/V",
    "Space 92 b2b Popof",
    "ATLiens",
    "Black Tiger Sex Machine",
    "HUGEL",
    "LF SYSTEM",
    "Eli Brown",
    "Layton Giordani",
    "Cloonee",
    "Max Styler",
    "Torren Foot",
    "ALLEYCVT",
    "Annicka",
    "ISOKNOCK",
    "Maddix",
    "Girl Math (VNSSA b2b Nala)",
    "NGHTMRE presents: MINDFULL",
    "Yellow Claw",
    "Loud Luxury",
    "SIDEPIECE",
    "Odd Mob",
    "Matroda",
    "Crankdat",
    "Tape B",
    "Dombresky",
    "Disco Lines",
    "Daniel Allan",
    "it's murph",
    "ARMNHMR",
    "AYYBO",
    "Baggi",
    "CHYL",
    "Brutalismus 3000",
    "GUDFELLA",
    "Hedex",
    "Oppidan",
    "Trivecta",
    "Villager",
    "Sosa b2b Classmatic",
    "BLOND:ISH",
    "Nico Moreno b2b I Hate Models",
    "Hot Since 82",
    "Dennis Cruz",
    "Funk Tribu b2b ØTTA",
    "Adam Ten b2b Mita Gami",
    "Ben Sterling b2b Rossi",
    "Alignment",
    "Airrica",
    "Beltran",
    "Carlita",
    "Clara Cuvé",
    "Cole Knight",
    "Masha Mar",
    "Selective Response",
    "SOSA",
    "southstar",
    "Paul Oakenfold",
    "Cosmic Gate",
    "Maddix b2b Ben Nicky",
    "Argy",
    "ARODES",
    "Avalon",
    "Ben Hemsley",
    "Billy Gillies",
    "Chris Avantgarde",
    "David Forbes",
    "David Rust",
    "Funk Tribu",
    "Hannah Laing",
    "Korolova",
    "Laura van Dam",
    "Lauren Mia",
    "Le Youth",
    "Lostly",
    "Marie Vaunt",
    "Miss Monique",
    "Miyuki",
    "Mr. Brooks",
    "Nils Hoffmann",
    "Omiki",
    "ØTTA",
    "Trance Wax",
    "Victor Ruiz",
    "Yoji Biomehanika",
    "Showtek (Hardstyle Set)",
    "Sub Zero Project",
    "Da Tweekaz",
    "Darren Styles",
    "D-Sturb",
    "Devin Wild",
    "Lil Texas",
    "Lady Faith",
    "Yosuf",
    "DEATH CODE b2b KAMI",
    "Dual Damage",
    "Mish",
    "Rooler",
    "OGUZ",
    "Shlømo",
    "Code Black",
    "Restricted",
    "Adrenalize",
    "ANGEL CANNON",
    "AniMe",
    "ANOLUXX",
    "Basswell",
    "BIIA",
    "Caravel",
    "Cera Khin",
    "Clawz",
    "Levenkhan",
    "Onlynumbers",
    "RayRay",
    "6ejou",
    "HUGEL & Friends",
    "Walker & Royce",
    "Disco Dom",
    "Interplanetary Criminal",
    "Francis Mercier",
    "Matroda & Friends",
    "Kyle Watson",
    "Pocket b2b Sam Binga",
    "33 Below b2b MPH",
    "Bontan b2b Calussa",
    "VNSSA",
    "OMNOM",
    "Linska",
    "Jackie Hollander",
    "Biscits",
    "Champion",
    "AMÉMÉ",
    "Amal Nemer",
    "Ahmed Spins",
    "Ky William",
    "Mattilo",
    "Maz",
    "RaeCola",
    "Riordan",
    "TWENTY SIX",
    "Wakyin",
    "Skream b2b Partiboi69",
    "Prospa b2b Josh Baker",
    "Fcukers (DJ Set)",
    "horsegiirL",
    "Dylan Brady",
    "Ben Sterling b2b Beltran",
    "Ben Sterling b2b Ahmed Spins",
    "Alex Chapman + Zoe Gitter",
    "DJ Fuckoff",
    "DJ Gigola",
    "INVT",
    "Lake Hills",
    "MALUGI",
    "MCR-T",
    "MRD",
    "Narciss",
    "OMRI",
    "Pablo Bozzi",
    "Slugg",
    "TDJ",
    "X CLUB",
  ],
} satisfies Festival;
