import type { Festival } from "@/lib/festivals";

const GRADIENT = "from-yellow-300 via-pink-500 to-fuchsia-600";

// 2022–2024 source: search summaries of stage-by-stage lineups and set times on edm.com, edmtunes.com,
// billboard.com, weraveyou.com, edmtrain.com, clashfinder.com (pages couldn't be fetched).

export const edc2022 = {
  id: "edc-las-vegas-2022",
  name: "EDC Las Vegas",
  year: 2022,
  startDate: "2022-05-20",
  location: "Las Vegas, NV",
  dates: "May 20–22",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Tiësto",
    "Zedd",
    "ILLENIUM",
    "DJ Snake",
    "Armin van Buuren",
    "David Guetta & MORTEN present Future Rave",
    "Kaskade & deadmau5 present Kx5",
    "Kaskade Redux",
    "Eric Prydz",
    "Alesso",
    "Porter Robinson (DJ Set)",
    "FISHER",
    "Chris Lake",
    "Charlotte de Witte",
    "Excision",
    "Zeds Dead",
    "REZZ",
    "Subtronics",
    "Seven Lions",
    "Grimes (DJ Set)",
    "Madeon (DJ Set)",
    "Tale Of Us",
    "Richie Hawtin",
    "Dom Dolla",
    "John Summit",
    "Alan Walker",
    "Alok",
    "Timmy Trumpet",
    "Vintage Culture",
    "Deorro",
    "Tchami",
    "San Holo",
    "Dillon Francis",
    "Jauz",
    "Yellow Claw",
    "Duck Sauce",
    "Above & Beyond",
    "Paul van Dyk",
    "Ferry Corsten",
    "Aly & Fila",
    "Cosmic Gate",
    "Vini Vici",
    "Gabriel & Dresden",
    "ATB",
    "Boris Brejcha",
    "Adam Beyer",
    "Joseph Capriati",
    "Kayzo",
    "Meduza",
    "ZHU",
    "SIDEPIECE",
    "Nora En Pure",
    "James Hype",
    "Jason Ross",
    "Luttrell",
    "Matroda",
    "Moore Kismet",
    "Lee Foss",
    "Ann Clue",
    "Blossom",
    "TESTPILOT",
    "Tinlicker",
    "Westend",
    "Acraze",
    "ARMNHMR",
    "Audien",
    "Autograf",
    "Cat Dealers",
    "Gem & Tauri",
    "Imanbek",
    "Joel Corry",
    "KREAM",
    "LP Giobbi",
    "AC Slater b2b Chris Lorenzo",
    "Nostalgix b2b Wenzday",
    "Blunts & Blondes",
    "Borgore",
    "EPROM",
    "G Jones",
    "Ganja White Night",
    "Liquid Stranger",
    "Rusko",
    "Zomboy",
    "1991",
    "A.M.C",
    "Alix Perez b2b Imanu",
    "ATLiens",
    "Bear Grillz b2b Kompany",
    "Definitive b2b Replicant",
    "Delta Heavy b2b Koven b2b Muzz",
    "Doctor P b2b FuntCase (Classics Set)",
    "Excision Detox",
    "Fallen b2b Richter",
    "Friction b2b Kanine",
    "Getter b2b Space Laces",
    "Hybrid Minds",
    "Jessica Audiffred",
    "Kai Wachi",
    "Lab Group",
    "Level Up",
    "Macky Gee",
    "Marauda",
    "Riot Ten",
    "Sub Focus & Wilkinson present Portals",
    "Subtronics b2b Boogie T",
    "SVDDEN DEATH",
    "Virtual Riot",
    "Headhunterz",
    "Wildstylez",
    "Da Tweekaz",
    "Sub Zero Project",
    "Darren Styles",
    "DJ Isaac",
    "Warface",
    "D-Sturb",
    "Adrenalize",
    "3 Blokes (Audiofreq / Code Black & Toneshifterz)",
    "Ben Nicky presents Xtreme",
    "Crime Family",
    "Darksiderz",
    "Deadly Guns",
    "Dr Phunk",
    "DJ Anime",
    "Hpnotic b2b Lucky Rabbit",
    "Junkie Kid b2b GEO",
    "KAMI",
    "Lady Faith",
    "Lil Texas",
    "Link",
    "LNY TNZ",
    "Mad Dog",
    "Omar Santana",
    "Radical Redemption",
    "Rob Gee",
    "SOREN",
    "Sound Rush",
    "Talon",
    "TNT",
    "Tweekacore",
    "A-Trak b2b Craze",
    "A-Trak (House Set)",
    "Air2Earth",
    "BIJOU b2b Habstrakt",
    "Diesel",
    "Evan Giia",
    "Gigantic NGHTMRE",
    "Good Times Ahead",
    "Hulk Gang (4B + Valentino Khan)",
    "Jai Wolf",
    "JSTJR",
    "K?D",
    "Kasablanca",
    "MitiS",
    "NITEPUNK",
    "Nitti Gritti b2b Wuki",
    "Partiboi69",
    "Qrion",
    "Shiba San",
    "So Tuff So Cute",
    "TSHA",
    "UNIIQU3",
    "Wax Motif",
    "Wenzday",
    "Westend b2b Lucati",
    "Whipped Cream",
    "Yolanda Be Cool",
    "Anfisa Letyago",
    "Avision",
    "Ben Böhmer (Live)",
    "Charlotte de Witte presents KNTXT",
    "Deborah De Luca",
    "Dennis Cruz",
    "Enrico Sangiuliano",
    "FJAAK (DJ Set)",
    "Honey Dijon",
    "I Hate Models",
    "Ilario Alicante",
    "Indira Paganotto",
    "Jayda G",
    "Ms. Mada",
    "Onyvaa",
    "Sinopoli b2b Danyelino",
    "Andrew Rayel",
    "Astrix",
    "Atdusk",
    "Craig Connelly",
    "Giuseppe Ottaviani Live 3.0",
    "HANA",
    "Ilan Bluestone",
    "John O'Callaghan",
    "Jorza",
    "Khromata",
    "Marlo",
    "Mat Zo",
    "Matt Fax",
    "Mr. Brooks",
    "Pretty Pink",
    "Renegade System",
    "Ruben de Ronde",
    "Schala",
    "Taylor Torrence",
    "Tempo Giusto",
    "Tritonal",
    "Xijaro & Pitch",
    "Alyx Ander",
    "Biscits",
    "Boston Bun",
    "Capozzi",
    "Chapter & Verse",
    "CID",
    "Cloonee",
    "Coco & Breezy",
    "Deeper Purpose",
    "Francis Mercier",
    "Gene Farris",
    "HoneyLuv",
    "HUGEL",
    "Jauz: Off The Deep End",
    "Joshwa",
    "LP Giobbi b2b Born Dirty",
    "Lucati",
    "Majestic",
    "Manolo",
    "Martin Ikin",
    "Mary Droppinz",
    "Matroda b2b Bleu Clair",
    "Nostalgix",
    "Sam Divine",
    "Vintage Culture b2b James Hype",
    "Volac",
    "Westend b2b Black V Neck",
    "Carl Craig",
    "Derrick Carter",
    "Felix da Housecat",
    "Mark Farina",
    "Marques Wyatt",
    "Harry Romero",
    "DJ Heather",
    "DJ Holographic",
    "Bakke",
    "Corey Sizemore b2b Richie Panic",
    "Heidi Lawden",
    "Masha Mar",
    "Things You Say",
    "Thunderpony",
  ],
} satisfies Festival;

export const edc2023 = {
  id: "edc-las-vegas-2023",
  name: "EDC Las Vegas",
  year: 2023,
  startDate: "2023-05-19",
  location: "Las Vegas, NV",
  dates: "May 19–21",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Martin Garrix",
    "Tiësto",
    "David Guetta",
    "Armin van Buuren",
    "Zedd",
    "Marshmello",
    "Kaskade",
    "Kaskade Redux",
    "Above & Beyond",
    "Alison Wonderland",
    "Chris Lake",
    "Excision b2b Dion Timmer",
    "GRiZ",
    "GRiZTRONICS",
    "Kaytranada",
    "The Prodigy",
    "Zeds Dead b2b Chase & Status",
    "Marshmello b2b SVDDEN DEATH",
    "FISHER",
    "Duke Dumont",
    "Vini Vici",
    "Boris Brejcha",
    "Galantis",
    "Gareth Emery",
    "Andy C",
    "Netsky",
    "AFROJACK",
    "Dom Dolla",
    "Subtronics",
    "Seven Lions",
    "Alok",
    "SLANDER",
    "Loud Luxury",
    "James Hype",
    "SIDEPIECE",
    "Valentino Khan",
    "Malaa b2b Wax Motif",
    "Tchami b2b AC Slater",
    "MORTEN",
    "Meduza",
    "Deorro",
    "Acraze",
    "Excision",
    "Ferry Corsten",
    "Cosmic Gate",
    "Lane 8",
    "Yotto",
    "Ben Nicky",
    "Will Atkinson",
    "Sultan + Shepard",
    "Carola",
    "Dombresky",
    "Fireworks",
    "Korolova",
    "KREAM",
    "Marten Hørger",
    "Pauline Herr",
    "Ship Wrek",
    "Anabel Englund",
    "Blanke",
    "Kill Script",
    "Modapit",
    "PEEKABOO",
    "SAYMYNAME",
    "Spencer Brown",
    "Tsu Nami",
    "12th Planet",
    "A Hundred Drums",
    "Barely Alive",
    "Bensley b2b Justin Hawkes",
    "Black Tiger Sex Machine",
    "Boogie T",
    "Borgore b2b Level Up",
    "Champagne Drip",
    "Dimension",
    "Eliminate",
    "Eptic",
    "Fallen b2b Richter with MC Dino",
    "Friction",
    "FuntCase",
    "Fury b2b Nightstalker",
    "Gentlemens Club",
    "HOL!",
    "HVDES",
    "IMANU",
    "Metrik b2b Grafix",
    "Midnight Tyrannosaurus",
    "Moody Good (Throwback Set)",
    "Ray Volpe",
    "Reaper",
    "Riot Ten b2b Jessica Audiffred",
    "Space Laces",
    "Sullivan King b2b Kai Wachi",
    "SVDDEN DEATH: Into The Inferno",
    "Wooli",
    "Brennan Heart",
    "Darren Styles",
    "DJ Isaac",
    "Sub Zero Project",
    "Ben Nicky presents Xtreme b2b Sub Zero Project",
    "Audiofreq",
    "Lil Texas",
    "Warface b2b D-Sturb",
    "Adrenalize",
    "AniMe",
    "Code Black",
    "Coone",
    "D-Sturb",
    "Da Tweekaz",
    "Deadly Guns",
    "Dionysus & Yosuf present Bigger, Stronger, Faster",
    "Dr Phunk",
    "Gammer b2b Tweekacore",
    "Lady Faith",
    "Lenny Dee",
    "Levenkhan",
    "Mrotek",
    "Omar Santana",
    "Rebelion",
    "Rob Gee 30 Years",
    "SHEI",
    "Softest Hard",
    "SOREN",
    "Sound Rush",
    "Suae",
    "Warface",
    "999999999",
    "ARTBAT",
    "Azzecca",
    "Eli Brown",
    "Ellen Allien",
    "Frame (Declan James & Decoder)",
    "Hint of Lavender",
    "Hot Since 82",
    "I Hate Models",
    "Jeff Mills",
    "Layla Benitez",
    "Loco Dice b2b FISHER",
    "The Martinez Brothers",
    "Mochakk",
    "Ms. Mada b2b Bakke",
    "Paco Osuna",
    "Patrick Topping",
    "PAWSA",
    "Reinier Zonneveld (Live)",
    "Will Clarke",
    "Mau P",
    "Nostalgix",
    "Chris Lorenzo",
    "Matroda",
    "Nala",
    "CID b2b Sage Armstrong",
    "Noizu",
    "JSTJR",
    "Habstrakt",
    "Tobehonest",
    "Capozzi",
    "J. Worra",
    "Abana",
    "Acraze b2b Noizu",
    "Biscits b2b Martin Ikin",
    "Bleu Clair",
    "Born Dirty",
    "Camden Cox",
    "Chaney",
    "CID",
    "Cloverdale",
    "Deeper Purpose",
    "Disco Lines",
    "Fallon",
    "Ferreck Dawn",
    "Goodboys",
    "Hannah Wants",
    "HUGEL",
    "Jaded",
    "Joshwa",
    "Kaleena Zanders",
    "Matroda & Friends",
    "Miane",
    "Miss Dre",
    "Odd Mob",
    "San Pacho",
    "Sonny Fodera",
    "Tom & Collins",
    "Westend",
    "AK Sports",
    "Baggi",
    "Ben UFO",
    "Danny Daze",
    "David Morales",
    "Dennis Ferrer",
    "Disco Dom",
    "DJ Minx",
    "Lady Sinclair",
    "Mike Dunn",
    "Things You Say",
  ],
} satisfies Festival;

export const edc2024 = {
  id: "edc-las-vegas-2024",
  name: "EDC Las Vegas",
  year: 2024,
  startDate: "2024-05-17",
  location: "Las Vegas, NV",
  dates: "May 17–19",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Martin Garrix",
    "Eric Prydz",
    "Tiësto",
    "Zedd",
    "David Guetta",
    "Armin van Buuren",
    "ILLENIUM",
    "Kaskade",
    "John Summit",
    "Dom Dolla",
    "deadmau5",
    "Alesso",
    "Peggy Gou",
    "Four Tet",
    "Alison Wonderland",
    "DJ Snake",
    "FISHER",
    "Excision",
    "Seven Lions",
    "Steve Aoki",
    "Diplo",
    "Subtronics",
    "Gryffin",
    "Carl Cox",
    "Adam Beyer",
    "Jamie Jones",
    "Sub Focus",
    "SLANDER",
    "Purple Disco Machine",
    "SOFI TUKKER (DJ Set)",
    "Lost Frequencies",
    "Benny Benassi",
    "Mau P",
    "Matroda",
    "MK",
    "Acraze & KREAM",
    "Wuki",
    "MitiS",
    "Maddix",
    "Öwnboss",
    "Ninajirachi",
    "RAYBEN",
    "ZueZeu",
    "Vintage Culture",
    "Kayzo",
    "Koven",
    "Cassian",
    "Christoph",
    "Airwolf Paradise",
    "Ben Hemsley",
    "Kyle Walker",
    "Wade",
    "Brina Knauss",
    "Sara Landry",
    "Eli Brown",
    "Green Velvet",
    "Trym",
    "Nightstalker",
    "Vulllgur",
    "Tape B",
    "LAYZ",
    "Jessica Audiffred",
    "NGHTMRE",
    "Zomboy",
    "Marauda",
    "HOL!",
    "Adventure Club",
    "Mersiv",
    "Fallen with MC Dino",
    "Chef Boyarbeatz",
    "Rated R",
    "Bou",
    "Wilkinson",
    "Wooli",
    "Hedex",
    "Subtronics b2b Level Up",
    "Boogie T",
    "Caspa",
    "Crankdat",
    "Richter",
    "JEANIE",
    "Zingara",
    "Emorfik",
    "Ghastly presents GHENGAR",
    "Dimension",
    "ATLiens",
    "SVDDEN DEATH",
    "Kai Wachi",
    "Virtual Riot",
    "Jon Casey",
    "Carl Cox b2b Nicole Moudaber",
    "Peggy Gou b2b Marcel Dettmann",
    "Nicole Moudaber",
    "Marcel Dettmann",
    "Loco Dice",
    "Deborah De Luca",
    "Indira Paganotto",
    "Joseph Capriati",
    "Lilly Palmer",
    "Klangkuenstler",
    "Adam X",
    "Ben Sterling",
    "Chelina Manuhutu",
    "Heidi Lawden",
    "Malóne",
    "Shlømo",
    "Dabin",
    "Deorro",
    "Devault",
    "Dillon Francis",
    "Friendly Fire",
    "FrostTop b2b RemK",
    "Hamdi",
    "HUGEL",
    "Joyryde b2b Habstrakt",
    "Kasablanca",
    "Khiva",
    "LSDREAM",
    "Mary Droppinz",
    "Noizu b2b Westend b2b Melé",
    "Odd Mob",
    "Sicaria",
    "TroyBoi",
    "Valentino Khan",
    "Camden Cox",
    "Deeper Purpose",
    "Paul van Dyk",
    "Paul Oakenfold (Full On Fluoro)",
    "Ferry Corsten",
    "Aly & Fila",
    "Markus Schulz",
    "Pryda",
    "Infected Mushroom",
    "Andrew Rayel",
    "Andrew Bayer",
    "Argy",
    "Alchimyst",
    "Blastoyz",
    "Bryan Kearney",
    "Daxson",
    "Giuseppe Ottaviani",
    "Jerome Isma-Ae",
    "John 00 Fleming",
    "Kevin de Vries",
    "KhoMha",
    "Luttrell",
    "Marsh",
    "Metta & Glyde",
    "Mind Against",
    "Miyuki",
    "Naz",
    "Nifra",
    "Nilsix (Ørjan Nilsen & Mark Sixma)",
    "Talla 2XLC",
    "Taylor Torrence",
    "Yotto",
    "Zof",
    "Majestic",
    "Riordan",
    "Max Styler",
    "Joluca",
    "Melé",
    "Hannah Laing",
    "Kevin Saunderson b2b DJ Minx",
    "Pocket",
    "Calussa",
    "Azzecca",
    "LF SYSTEM",
    "Shiba San",
    "Angerfist",
    "Atmozfears",
    "Audiofreq",
    "Adrenalize b2b Wasted Penguinz",
    "Wasted Penguinz",
    "D-Sturb",
    "Da Tweekaz",
    "Devin Wild b2b Keltek",
    "Devin Wild",
    "Keltek",
    "GEO",
    "GRAVEDGR",
    "Hixxy",
    "Lady Faith",
    "Sound Rush",
    "Sub Zero Project",
    "Yosuf",
    "Dead X b2b Levenkhan",
    "Clawz b2b DØMINA",
    "Kreation b2b Darksiderz",
    "Hivemind (Kayzo x Space Laces x Must Die!)",
    "Deadly Guns",
    "DEATH CODE",
    "SOREN",
    "Warface",
    "Water Spirit",
    "Boys Noize",
    "Bianca Oblivion",
    "Denis Sulta",
    "Interplanetary Criminal",
    "Panteros666",
    "Ranger Trucco",
    "Sally C",
    "Skin On Skin",
    "X-Coast",
  ],
} satisfies Festival;

// Source: search summaries of edm.com, edmidentity.com, djmag.com, press.insomniac.com,
// lasvegassun.com, weraveyou.com (pages couldn't be fetched). ~125 of ~247 artists.
export const edc2026 = {
  id: "edc-las-vegas-2026",
  name: "EDC Las Vegas",
  year: 2026,
  startDate: "2026-05-15",
  location: "Las Vegas, NV",
  dates: "May 15–17",
  gradient: "from-yellow-300 via-pink-500 to-fuchsia-600",
  partial: true,
  lineup: [
    "Martin Garrix",
    "Tiësto",
    "Zedd",
    "The Chainsmokers",
    "Kaskade",
    "John Summit",
    "FISHER",
    "Charlotte de Witte",
    "Armin van Buuren",
    "Above & Beyond",
    "Steve Aoki",
    "Porter Robinson",
    "Subtronics",
    "Chris Lake",
    "The Prodigy",
    "Underworld",
    "Alison Wonderland",
    "Seven Lions",
    "GRiZ b2b Wooli",
    "Paul van Dyk",
    "Peggy Gou",
    "Sub Focus",
    "Adventure Club",
    "Pegassi",
    "Darude",
    "San Holo",
    "Gareth Emery",
    "Paul Oakenfold",
    "Eli & Fur",
    "Tinlicker",
    "Ilan Bluestone",
    "Sarah de Warren",
    "Innellea",
    "MPH",
    "San Pacho",
    "Interplanetary Criminal",
    "MALUGI",
    "Snow Strippers",
    "Hannah Laing",
    "Chris Stussy",
    "Levity",
    "Lilly Palmer",
    "Beltran",
    "Nico Moreno",
    "KETTAMA",
    "Joseph Capriati",
    "Eli Brown",
    "Indira Paganotto",
    "Klangkuenstler",
    "Prospa",
    "Frankie Bones",
    "KI/KI",
    "Holy Priest",
    "Restricted",
    "Sub Zero Project",
    "Lil Texas",
    "Kuko b2b Johannes Schuster",
    "GRAVEDGR",
    "Robe Gee b2b Lenny Dee",
    "Lady Faith b2b LNY TNZ",
    "Audiofreq b2b Code Black b2b Toneshifterz",
    "Noizu",
    "OMNOM",
    "Wax Motif",
    "BOLO",
    "Luuk van Dijk",
    "Luke Dean",
    "Josh Baker",
    "Max Dean b2b Luke Dean",
    "Abana b2b Juliet Mendoza",
    "Sidney Charles b2b Bushbaby",
    "Chris Lorenzo b2b Bullet Tooth",
    "DJ Tennis b2b Red Axes",
    "MCR-T",
    "Paramida",
    "SALUTE b2b Chloé Caillet",
    "BAUGRUPPE90",
    "Heidi Lawden b2b Masha Mar",
    "HAAi b2b Luke Alessi",
    "ÆON:MODE",
    "ATLiens",
    "AHEE b2b Liquid Stranger",
    "INFEKT b2b Samplifire",
    "Avello b2b Dennett",
    "Boogie T b2b Distinct Motive",
    "Culture Shock",
    "Delta Heavy",
    "EAZYBAKED",
    "Eptic b2b Space Laces",
    "Fallen with MC Dino",
    "GHENGAR",
    "Getter",
    "GorillaT",
    "HEYZ",
    "HOL!",
    "Hybrid Minds",
    "Kai Wachi",
    "Muzz",
    "Mary Droppinz",
    "Nightstalker with MC Dino",
    "Viperactive",
    "Whethan",
    "Wooli",
    "YDG",
    "Doctor P b3b Flux Pavilion b3b FuntCase",
    "Josh Baker b3b KETTAMA b3b Prospa",
    "Walker & Royce b2b VNSSA",
    "Laidback Luke b2b Chuckie",
    "Beltran b2b Simas",
  ],
} satisfies Festival;

// Source: search summaries of lasvegas.edc.com, edmidentity.com, djmag.com, jambase.com set times
// and stage lists (pages couldn't be fetched). 9 main stages near-complete; art cars not included.
export const edc2025 = {
  id: "edc-las-vegas-2025",
  name: "EDC Las Vegas",
  year: 2025,
  startDate: "2025-05-16",
  location: "Las Vegas, NV",
  dates: "May 16–18",
  gradient: "from-yellow-300 via-pink-500 to-fuchsia-600",
  partial: true,
  lineup: [
    "Tiësto",
    "Martin Garrix",
    "Armin van Buuren",
    "Eric Prydz",
    "Kaskade",
    "Alesso",
    "Dom Dolla",
    "DJ Snake",
    "FISHER",
    "ILLENIUM b2b SLANDER",
    "AFROJACK",
    "Charlotte de Witte",
    "Excision",
    "REZZ",
    "Gesaffelstein",
    "Alison Wonderland b2b Kaskade",
    "RL Grime",
    "Chase & Status",
    "Sara Landry",
    "Amelie Lens",
    "Gorgon City",
    "Meduza",
    "James Hype",
    "Marlon Hoffstadt",
    "Mau P",
    "Mochakk",
    "Pryda",
    "Vini Vici",
    "Bicep presents Chroma",
    "Boys Noize",
    "TOKiMONSTA",
    "Andy C",
    "Skepta Más Tiempo",
    "Vintage Culture",
    "The Martinez Brothers b2b Loco Dice",
    "ARTBAT b2b MORTEN",
    "SLANDER b2b NGHTMRE",
    "Nora En Pure",
    "Alok",
    "Deorro & Friends",
    "Mike Posner",
    "Danny Avila",
    "Ben Nicky",
    "Dimension",
    "Xandra",
    "Noizu",
    "Lavern",
    "SVDDEN DEATH",
    "Sullivan King",
    "Liquid Stranger",
    "Levity",
    "Netsky",
    "Apashe",
    "Ray Volpe",
    "Riot Ten",
    "Caspa b2b Rusko",
    "Crankdat b2b Tape B",
    "Basstripper b2b Sota",
    "Jessica Audiffred b2b LAYZ",
    "RZRKT b2b Vastive",
    "AHEE",
    "Andromedik",
    "Distinct Motive",
    "DRINKURWATER",
    "Fury with MC Dino",
    "INFEKT",
    "INZO",
    "Kompany",
    "Level Up",
    "Of The Trees",
    "Rudim3ntal",
    "Samplifire",
    "Shades",
    "Simula",
    "Soothslayer",
    "Steller",
    "Truth",
    "YDG",
    "Armand Van Helden",
    "Tchami x Malaa: No Redemption",
    "I Hate Models presents Face II Face A/V",
    "Space 92 b2b Popof",
    "ATLiens",
    "Black Tiger Sex Machine",
    "HUGEL",
    "LF SYSTEM",
    "Eli Brown",
    "Layton Giordani",
    "Cloonee",
    "Max Styler",
    "Torren Foot",
    "ALLEYCVT",
    "Annicka",
    "ISOKNOCK",
    "Maddix",
    "Girl Math (VNSSA b2b Nala)",
    "NGHTMRE presents: MINDFULL",
    "Yellow Claw",
    "Loud Luxury",
    "SIDEPIECE",
    "Odd Mob",
    "Matroda",
    "Crankdat",
    "Tape B",
    "Dombresky",
    "Disco Lines",
    "Daniel Allan",
    "it's murph",
    "ARMNHMR",
    "AYYBO",
    "Baggi",
    "CHYL",
    "Brutalismus 3000",
    "GUDFELLA",
    "Hedex",
    "Oppidan",
    "Trivecta",
    "Villager",
    "Sosa b2b Classmatic",
    "BLOND:ISH",
    "Nico Moreno b2b I Hate Models",
    "Hot Since 82",
    "Dennis Cruz",
    "Funk Tribu b2b ØTTA",
    "Adam Ten b2b Mita Gami",
    "Ben Sterling b2b Rossi",
    "Alignment",
    "Airrica",
    "Beltran",
    "Carlita",
    "Clara Cuvé",
    "Cole Knight",
    "Masha Mar",
    "Selective Response",
    "SOSA",
    "southstar",
    "Paul Oakenfold",
    "Cosmic Gate",
    "Maddix b2b Ben Nicky",
    "Argy",
    "ARODES",
    "Avalon",
    "Ben Hemsley",
    "Billy Gillies",
    "Chris Avantgarde",
    "David Forbes",
    "David Rust",
    "Funk Tribu",
    "Hannah Laing",
    "Korolova",
    "Laura van Dam",
    "Lauren Mia",
    "Le Youth",
    "Lostly",
    "Marie Vaunt",
    "Miss Monique",
    "Miyuki",
    "Mr. Brooks",
    "Nils Hoffmann",
    "Omiki",
    "ØTTA",
    "Trance Wax",
    "Victor Ruiz",
    "Yoji Biomehanika",
    "Showtek (Hardstyle Set)",
    "Sub Zero Project",
    "Da Tweekaz",
    "Darren Styles",
    "D-Sturb",
    "Devin Wild",
    "Lil Texas",
    "Lady Faith",
    "Yosuf",
    "DEATH CODE b2b KAMI",
    "Dual Damage",
    "Mish",
    "Rooler",
    "OGUZ",
    "Shlømo",
    "Code Black",
    "Restricted",
    "Adrenalize",
    "ANGEL CANNON",
    "AniMe",
    "ANOLUXX",
    "Basswell",
    "BIIA",
    "Caravel",
    "Cera Khin",
    "Clawz",
    "Levenkhan",
    "Onlynumbers",
    "RayRay",
    "6ejou",
    "HUGEL & Friends",
    "Walker & Royce",
    "Disco Dom",
    "Interplanetary Criminal",
    "Francis Mercier",
    "Matroda & Friends",
    "Kyle Watson",
    "Pocket b2b Sam Binga",
    "33 Below b2b MPH",
    "Bontan b2b Calussa",
    "VNSSA",
    "OMNOM",
    "Linska",
    "Jackie Hollander",
    "Biscits",
    "Champion",
    "AMÉMÉ",
    "Amal Nemer",
    "Ahmed Spins",
    "Ky William",
    "Mattilo",
    "Maz",
    "RaeCola",
    "Riordan",
    "TWENTY SIX",
    "Wakyin",
    "Skream b2b Partiboi69",
    "Prospa b2b Josh Baker",
    "Fcukers (DJ Set)",
    "horsegiirL",
    "Dylan Brady",
    "Ben Sterling b2b Beltran",
    "Ben Sterling b2b Ahmed Spins",
    "Alex Chapman + Zoe Gitter",
    "DJ Fuckoff",
    "DJ Gigola",
    "INVT",
    "Lake Hills",
    "MALUGI",
    "MCR-T",
    "MRD",
    "Narciss",
    "OMRI",
    "Pablo Bozzi",
    "Slugg",
    "TDJ",
    "X CLUB",
  ],
} satisfies Festival;
