import type { Festival } from "@/lib/festivals";

// Source: search summaries of relix.com, edmidentity.com, edmtunes.com, jambase.com,
// festivawl.com, billboard.com (pages couldn't be fetched). ~92 of ~130–150 artists.
export const electricForest2026 = {
  id: "electric-forest-2026",
  name: "Electric Forest",
  year: 2026,
  startDate: "2026-06-25",
  location: "Rothbury, MI",
  dates: "Jun 25–28",
  gradient: "from-emerald-300 via-teal-400 to-violet-500",
  partial: true,
  lineup: [
    "ILLENIUM",
    "Excision",
    "Kaskade",
    "GRiZ",
    "Chris Lake",
    "The String Cheese Incident",
    "Sammy Virji",
    "Disco Lines",
    "Levity",
    "ISOxo",
    "Madeon",
    "Purple Disco Machine",
    "Lane 8",
    "Galantis",
    "Passion Pit",
    "Shpongle",
    "DJ Diesel b2b T-Pain",
    "LSDREAM",
    "Channel Tres",
    "Ganja White Night",
    "SBTRKT (DJ Set)",
    "Eli Brown",
    "Sullivan King",
    "Bob Moses",
    "SIDEPIECE",
    "Claude VonStroke",
    "Odd Mob",
    "Tourist",
    "Wooli",
    "ALLEYCVT",
    "underscores",
    "Frost Children",
    "Daily Bread",
    "Yaeji",
    "EOTO",
    "Rochelle Jordan",
    "Sam Gellaitry",
    "Jean Dawson",
    "Iniko",
    "INJI",
    "Night Tapes",
    "Daniel Donato's Cosmic Country",
    "Eggy",
    "Dogs In A Pile",
    "Couch",
    "Stolen Gin",
    "Aron Magner & Cloudchord present DEADTRONICA",
    "Saint Ludo",
    "Bombargo",
    "Dixon's Violin",
    "Effin",
    "Midnight Generation",
    "Ship Wrek",
    "Kaleena Zanders",
    "MUZZ",
    "NITEPUNK",
    "Łaszewo",
    "Westend",
    "D.O.D",
    "Devault",
    "Discovery Project",
    "Close Friends Only",
    "Daniel Allan",
    "Tiffany Day",
    "H&RRY",
    "Jackie Hollander",
    "Ivy Lab",
    "Motifv",
    "MCR-T",
    "OMNOM",
    "Qrion",
    "CASEY CLUB",
    "CREG",
    "Chmura",
    "Lyrah",
    "all:Lo Collective",
    "Parkbreezy",
    "pheel.",
    "TF Marz",
    "Thought Process",
    "Jkyl & Hyde b2b Nikita the Wicked",
    "Cain Culto",
    "Magoo",
  ],
} satisfies Festival;
