import type { Festival } from "@/lib/festivals";

const GRADIENT = "from-emerald-300 via-teal-400 to-violet-500";

// 2022–2025 source: search summaries of billboard.com, relix.com, liveforlivemusic.com, jambase.com,
// edm.com, edmidentity.com, electricfamily.com (pages couldn't be fetched).

// First edition after the 2020–2021 hiatus.
export const electricForest2022 = {
  id: "electric-forest-2022",
  name: "Electric Forest",
  year: 2022,
  startDate: "2022-06-23",
  location: "Rothbury, MI",
  dates: "Jun 23–26",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "The String Cheese Incident",
    "GRiZ",
    "Porter Robinson",
    "Disclosure",
    "Louis The Child",
    "The Disco Biscuits",
    "Big Gigantic",
    "SLANDER",
    "FISHER",
    "Sylvan Esso",
    "CloZee",
    "Duke Dumont",
    "Subtronics",
    "TOKiMONSTA",
    "Toro y Moi",
    "Yves Tumor",
    "Cory Henry",
    "Deathpact",
    "Femi Kuti",
    "EARTHGANG",
    "Michigander",
    "Joe Hertler & The Rainbow Seekers",
    "Big Wild",
    "Chelsea Cutler",
    "EVAN GIIA",
    "Lettuce",
    "Lotus",
    "John Summit",
    "Dom Dolla",
    "Zeds Dead",
    "Fred again..",
    "Air2Earth",
    "Rainbow Kitten Surprise",
    "The Knocks",
    "12th Planet",
    "DJ Holographic",
    "Chiiild",
    "midwxst",
  ],
} satisfies Festival;

export const electricForest2023 = {
  id: "electric-forest-2023",
  name: "Electric Forest",
  year: 2023,
  startDate: "2023-06-22",
  location: "Rothbury, MI",
  dates: "Jun 22–25",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "The String Cheese Incident",
    "ODESZA",
    "ILLENIUM",
    "Zeds Dead",
    "Above & Beyond",
    "Jamie xx",
    "FLETCHER",
    "STS9",
    "Gryffin",
    "Lane 8",
    "REZZ",
    "SOFI TUKKER",
    "Goose",
    "Ganja White Night",
    "Chris Lake",
    "Madeon",
    "Chromeo",
    "070 Shake",
    "BLOND:ISH",
    "Channel Tres",
    "Chris Lorenzo",
    "DIESEL",
    "Emotional Oranges",
    "GASHI",
    "Gorgon City",
    "Hayden James",
    "Kai Wachi",
    "MEUTE",
    "PEEKABOO",
    "San Holo",
    "SG Lewis",
    "Barry Can't Swim",
    "Saka",
    "Snakes & Stars",
    "Bob Moses (Club Set)",
    "Cosmic Gate",
    "Dabin",
    "Infected Mushroom",
    "Kerala Dust",
    "Rusko b2b Dirt Monkey",
    "Sad Night Dynamite",
    "Totally Enormous Extinct Dinosaurs",
    "Two Feet",
    "Walker & Royce",
    "AMÉMÉ",
    "Bontan",
    "Coco & Clair Clair",
    "Daniel Allan",
    "Devault",
    "DJ Brownie",
    "Dr. Fresch",
    "EAZYBAKED",
    "Elohim",
    "ford.",
    "Forester",
    "Kainalu",
    "Kasablanca",
    "Kasbo",
    "Lee Foss",
    "Malóne",
    "MEMBA",
    "Miane",
    "N3ptune + Rusty Steve",
    "PawPaw Rod",
    "Phantoms",
    "DJ Politik",
    "Tape B",
    "Tkay Maidza",
    "Truth",
    "Very Nice Person",
    "Yunè Pinku",
  ],
} satisfies Festival;

export const electricForest2024 = {
  id: "electric-forest-2024",
  name: "Electric Forest",
  year: 2024,
  startDate: "2024-06-20",
  location: "Rothbury, MI",
  dates: "Jun 20–23",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Pretty Lights",
    "Excision",
    "Subtronics",
    "Everything Always (Dom Dolla + John Summit)",
    "The String Cheese Incident",
    "Charlotte de Witte",
    "Nelly Furtado",
    "Ludacris",
    "PSYREN (CloZee + LSDREAM)",
    "Gigantic NGHTMRE",
    "Black Tiger Sex Machine",
    "The Disco Biscuits",
    "Umphrey's McGee",
    "Ben Böhmer",
    "Knock2",
    "Seven Lions",
    "Mau P",
    "LP Giobbi",
    "DJ Tennis",
    "Sultan + Shepard",
    "TSHA",
    "Coco & Breezy",
    "Chase & Status",
    "Barclay Crenshaw",
    "ATLiens",
    "Wooli",
    "Whyte Fang",
    "ACRAZE",
    "ALLEYCVT",
    "AYYBO",
    "Calussa",
    "Cannons",
    "Caspa",
    "Cassian",
    "Cuco",
    "Dimension",
    "Dirtwire",
    "Dixon's Violin",
    "DRAMA",
    "Dumpstaphunk",
    "Eggy",
    "Green Velvet",
    "Hamdi",
    "INZO",
    "it's murph",
    "John Summit",
    "Juelz",
    "Kenny Beats",
    "Le Youth",
    "Lettuce",
    "Level Up",
    "Libianca",
    "Luci",
    "LYNY",
    "Maddy O'Neal",
    "Major League DJz",
    "G Jones",
    "Sara Landry",
    "Hiatus Kaiyote",
    "Layton Giordani",
    "Chaos in The CBD",
    "Brandi Cyrus",
    "Emo Nite",
    "Boogie T",
    "Levity",
    "Odd Mob",
    "HYPERBEAM",
    "Marsh",
    "DJ Susan",
    "Canabliss",
    "Little Stranger",
    "Mojave Grey",
    "Only Fire",
    "Baggi",
    "Super Future",
    "SWAYLÓ",
    "Redrum",
    "Polyrhythmics",
  ],
} satisfies Festival;

// Kanine and Jersey cancelled. WORSHIP = Dimension, Sub Focus, Culture Shock & 1991.
export const electricForest2025 = {
  id: "electric-forest-2025",
  name: "Electric Forest",
  year: 2025,
  startDate: "2025-06-19",
  location: "Rothbury, MI",
  dates: "Jun 19–22",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Justice",
    "FISHER",
    "Tiësto",
    "Disclosure (DJ Set)",
    "Khruangbin",
    "Louis The Child",
    "The String Cheese Incident",
    "Zeds Dead presents Return To The Spectrum Of Intergalactic Happiness",
    "Sara Landry",
    "Liquid Stranger",
    "WORSHIP",
    "Barry Can't Swim",
    "Of The Trees",
    "Mochakk",
    "Caribou",
    "Nia Archives",
    "Say She She",
    "Gordo",
    "Cloonee",
    "BLOND:ISH",
    "Lilly Palmer",
    "Loco Dice",
    "Mersiv",
    "Crankdat",
    "Hamdi",
    "YDG",
    "Zingara",
    "Jade Cicada",
    "BAMBII",
    "Arc De Soleil",
    "Tape B",
    "Vintage Culture",
    "Daphni",
    "Mike Posner",
    "Dombresky presents Disco Dom",
    "The Knocks & Dragonette",
    "Dimension",
    "Sub Focus",
    "Culture Shock",
    "Notion",
    "Will Clarke",
    "HAYLA",
    "Smoakland",
    "VEIL",
    "Lumasi",
    "Austeria",
    "BUNT.",
    "Ray Volpe",
    "SunSquabi",
    "DJ Brownie",
    "DJ Heartstring",
    "Interplanetary Criminal",
    "BLAAP",
    "DJ Sphinx",
    "Esseks",
    "Wreckno's Big Gay Soiree",
    "Brandi Cyrus",
    "Halfcab",
  ],
} satisfies Festival;

// Source: search summaries of relix.com, edmidentity.com, edmtunes.com, jambase.com,
// festivawl.com, billboard.com (pages couldn't be fetched). ~92 of ~130–150 artists.
export const electricForest2026 = {
  id: "electric-forest-2026",
  name: "Electric Forest",
  year: 2026,
  startDate: "2026-06-25",
  location: "Rothbury, MI",
  dates: "Jun 25–28",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "ILLENIUM",
    "Excision",
    "Kaskade",
    "GRiZ",
    "Chris Lake",
    "The String Cheese Incident",
    "Sammy Virji",
    "Disco Lines",
    "Levity",
    "ISOxo",
    "Madeon",
    "Purple Disco Machine",
    "Lane 8",
    "Galantis",
    "Passion Pit",
    "Shpongle",
    "DJ Diesel b2b T-Pain",
    "LSDREAM",
    "Channel Tres",
    "Ganja White Night",
    "SBTRKT (DJ Set)",
    "Eli Brown",
    "Sullivan King",
    "Bob Moses",
    "SIDEPIECE",
    "Claude VonStroke",
    "Odd Mob",
    "Tourist",
    "Wooli",
    "ALLEYCVT",
    "underscores",
    "Frost Children",
    "Daily Bread",
    "Yaeji",
    "EOTO",
    "Rochelle Jordan",
    "Sam Gellaitry",
    "Jean Dawson",
    "Iniko",
    "INJI",
    "Night Tapes",
    "Daniel Donato's Cosmic Country",
    "Eggy",
    "Dogs In A Pile",
    "Couch",
    "Stolen Gin",
    "Aron Magner & Cloudchord present DEADTRONICA",
    "Saint Ludo",
    "Bombargo",
    "Dixon's Violin",
    "Effin",
    "Midnight Generation",
    "Ship Wrek",
    "Kaleena Zanders",
    "MUZZ",
    "NITEPUNK",
    "Łaszewo",
    "Westend",
    "D.O.D",
    "Devault",
    "Discovery Project",
    "Close Friends Only",
    "Daniel Allan",
    "Tiffany Day",
    "H&RRY",
    "Jackie Hollander",
    "Ivy Lab",
    "Motifv",
    "MCR-T",
    "OMNOM",
    "Qrion",
    "CASEY CLUB",
    "CREG",
    "Chmura",
    "Lyrah",
    "all:Lo Collective",
    "Parkbreezy",
    "pheel.",
    "TF Marz",
    "Thought Process",
    "Jkyl & Hyde b2b Nikita the Wicked",
    "Cain Culto",
    "Magoo",
  ],
} satisfies Festival;
