import type { Festival } from "@/lib/festivals";

// Source: search summaries of press.insomniac.com, edmidentity.com, electronicgroove.com,
// edmtunes.com, djlifemag.com (pages couldn't be fetched). ~63 of 80+ artists.
export const escape2026 = {
  id: "escape-2026",
  name: "Escape Psycho Circus",
  year: 2026,
  startDate: "2026-10-30",
  location: "San Bernardino, CA",
  dates: "Oct 30–31",
  gradient: "from-orange-400 via-red-500 to-purple-700",
  partial: true,
  lineup: [
    "Zedd",
    "Ice Cube",
    "Excision",
    "Richie Hawtin",
    "Dimitri Vegas & Like Mike",
    "Galantis",
    "Steve Aoki",
    "Benny Benassi",
    "Alok",
    "Morten",
    "Cloonee",
    "Disco Lines",
    "Jamie Jones b2b Franky Rizardo",
    "Joseph Capriati b2b SOSA",
    "Indira Paganotto",
    "Nina Kraviz",
    "Showtek (Hardstyle Set)",
    "Cascada",
    "NERVO",
    "Adventure Club",
    "Liquid Stranger",
    "999999999",
    "AC Slater",
    "Adam Ten",
    "Avalon Emerson",
    "AZYR",
    "Bou",
    "Cera Khin",
    "Clara Cuvé",
    "Dabin",
    "Darren Styles",
    "DJ Heartstring",
    "DJ Tennis",
    "Dr. Fresch",
    "Frontliner (Journey Set)",
    "Funk Assault",
    "Gammer",
    "Getter",
    "Ian Asher",
    "Jon Casey",
    "Joyryde (Sunset Set)",
    "K?d Presents: Kill The Kid",
    "Kai Wachi",
    "Kana Hishiya",
    "KLOUD",
    "KREAM",
    "Lady Faith b2b LNY TNZ",
    "Level Up",
    "Maddix",
    "Malugi",
    "OMNOM",
    "San Pacho",
    "Silvie Loto",
    "TELYKAST",
    "Trancemaster Krause",
    "Trym",
    "YDG",
    "Alex Chapman b2b Zoe Gitter",
    "Andruss b2b Juos",
    "Cat & Maomi",
    "Pedroz",
    "Rommii",
    "Yanamaste",
  ],
} satisfies Festival;

// Source: search summaries of edmidentity.com, musicfestivalwizard.com, globaldanceelectronic.com,
// clashfinder.com set times (pages couldn't be fetched). Believed complete (~68 artists).
export const escape2022 = {
  id: "escape-2022",
  name: "Escape Halloween",
  year: 2022,
  startDate: "2022-10-28",
  location: "San Bernardino, CA",
  dates: "Oct 28–29",
  gradient: "from-orange-400 via-red-500 to-purple-700",
  lineup: [
    "Marshmello",
    "Tiësto",
    "Martin Garrix",
    "Eric Prydz",
    "Diplo",
    "Alesso",
    "Subtronics",
    "Oliver Heldens",
    "Black Tiger Sex Machine",
    "Deorro b2b Valentino Khan",
    "Said The Sky",
    "Nina Kraviz",
    "Marco Carola",
    "Vintage Culture",
    "Kayzo",
    "100 gecs",
    "Getter b2b Eptic",
    "Flosstradamus",
    "SIDEPIECE",
    "Bob Moses (Club Set)",
    "Meduza",
    "Deborah De Luca",
    "Ben Klock",
    "ANNA",
    "Eli Brown",
    "Wax Motif",
    "Radical Redemption",
    "Sub Zero Project",
    "D-Sturb b2b Warface",
    "Da Tweekaz",
    "Ben Nicky presents Xtreme",
    "DJ Anime",
    "Lucii",
    "SAYMYNITTI",
    "Moore Kismet",
    "Nurko (Nightfall Set)",
    "Wooli",
    "Modestep",
    "Calcium",
    "The Prototypes",
    "Zingara",
    "Cloonee",
    "Anfisa Letyago",
    "Chris Stussy",
    "HoneyLuv",
    "J. Worra",
    "Brennen Grey",
    "Drakk",
    "Miane",
    "Bones",
    "KLOUD",
    "Florian Picasso",
    "Kill Script",
    "BIJOU",
    "Blossom",
    "KROMI",
    "Dot",
    "Pauline Herr",
    "FrostTop",
    "Shiverz",
    "Skellytn",
    "Sound Rush",
    "Lucky Rabbit",
    "SOREN",
    "Kreation",
  ],
} satisfies Festival;
