import type { Festival } from "@/lib/festivals";

// 2023–2025 source: search summaries of jambase.com, edmtunes.com, edmidentity.com, edm.com,
// broadwayworld.com, festivaldust.com (pages couldn't be fetched). Branded "Escape Halloween" in
// 2023–2024 and "Escape Psycho Circus" from 2025; all named "Escape" here so the years group together.

export const escape2023 = {
  id: "escape-2023",
  name: "Escape",
  year: 2023,
  startDate: "2023-10-27",
  location: "San Bernardino, CA",
  dates: "Oct 27–28",
  gradient: "from-orange-400 via-red-500 to-purple-700",
  partial: true,
  lineup: [
    "Above & Beyond",
    "Armin van Buuren",
    "Zedd",
    "Kaskade",
    "DJ Snake",
    "AFROJACK",
    "SLANDER",
    "REZZ",
    "Tchami",
    "Malaa",
    "Three 6 Mafia",
    "Green Velvet",
    "Jamie Jones",
    "Hot Since 82",
    "Loco Dice",
    "ARMNHMR",
    "ATLiens",
    "Ben Nicky presents Xtreme",
    "Black Sun Empire b2b The Upbeats (20 Years of Black Out)",
    "Buns",
    "Calyx",
    "Canabliss",
    "Charles D",
    "Chelina Manuhutu",
    "CID b3b HUGEL b3b Westend",
    "Code Black: Blackout",
    "Codeko",
    "Crystal Skies",
    "Culture Shock",
    "Danny Olson",
    "Darren Styles",
    "Deathpact",
    "DJ Isaac b2b SAYMYNAME",
    "DJ Topgun",
    "Ed Rush & Optical",
    "HE$H",
    "Ian Asher",
    "JVNA",
    "K?D",
    "Kaivon",
    "KAS:ST",
    "KELTEK",
    "Lady Faith",
    "Lauren Lane",
    "Lilly Palmer",
    "LNY TNZ",
    "Macky Gee",
    "Mariana BO",
    "Matroda",
    "Max Styler",
    "MK",
    "Musubi",
    "Nia Archives",
    "NITEPUNK",
    "Patrick Topping",
    "Reinier Zonneveld",
    "Rohaan",
    "ROSSY",
    "Senza",
    "Ship Wrek",
    "Skellytn",
    "Space 92 x Popof present TURBULENCES",
    "SUAHN",
    "SVDDEN DEATH",
    "Taylor Kade",
    "Tobehonest",
    "Wade",
    "Wilkinson",
    "William Black",
    "Yetep",
    "Zomboy",
  ],
} satisfies Festival;

export const escape2024 = {
  id: "escape-2024",
  name: "Escape",
  year: 2024,
  startDate: "2024-10-25",
  location: "San Bernardino, CA",
  dates: "Oct 25–26",
  gradient: "from-orange-400 via-red-500 to-purple-700",
  partial: true,
  lineup: [
    "ILLENIUM",
    "Martin Garrix",
    "Afroki (AFROJACK b2b Steve Aoki)",
    "deadmau5",
    "Fatboy Slim",
    "Ludacris",
    "Alison Wonderland",
    "Seven Lions",
    "MEDUZA",
    "Nina Kraviz",
    "Ben Klock b2b Marcel Dettmann",
    "Adventure Club",
    "ANGEL CANNON",
    "Angerfist",
    "Ben Nicky",
    "Capozzi",
    "Cherry Lee",
    "Chippy Nonstop",
    "Chloé Caillet",
    "Clara Cuvé",
    "Cloonee",
    "Da Tweekaz",
    "Daizy",
    "Denis Sulta",
    "Dennis Cruz",
    "Dixon",
    "DJ Zo",
    "Dog Eat Dog (Crankdat b2b Riot Ten)",
    "Don Diablo",
    "Fallon",
    "Ghastly presents GHENGAR",
    "HVDES",
    "James Hype",
    "Joshwa",
    "KELTEK",
    "KREAM",
    "Lady Faith",
    "Level Up",
    "Lil Texas",
    "Lost Frequencies",
    "Mary Droppinz",
    "Netsky",
    "Odd Mob",
    "OGUZ",
    "OMNOM",
    "PAWSA",
    "PEEKABOO",
    "Prunk",
    "Rebekah",
    "Rooler",
    "Snakehips",
    "SWIM",
    "Tony Junior",
    "Trivecta",
    "Two Friends",
    "Vastive",
    "Wooli",
    "Young Marco",
  ],
} satisfies Festival;

export const escape2025 = {
  id: "escape-2025",
  name: "Escape",
  year: 2025,
  startDate: "2025-10-31",
  location: "San Bernardino, CA",
  dates: "Oct 31–Nov 1",
  gradient: "from-orange-400 via-red-500 to-purple-700",
  partial: true,
  lineup: [
    "Marshmello b2b DJ Snake",
    "Porter Robinson (DJ Set)",
    "deadmau5",
    "Alesso",
    "Dimitri Vegas",
    "RL Grime",
    "RL Grime Sable Valley Takeover",
    "Amelie Lens",
    "The Martinez Brothers",
    "Vintage Culture",
    "Virtual Riot",
    "Gryffin",
    "San Holo (Wholesome Riddim Set)",
    "What So Not",
    "TroyBoi",
    "KSHMR b2b R3HAB",
    "NGHTMRE b2b PEEKABOO",
    "Nicole Moudaber b2b Ilario Alicante",
    "Clawz b2b Luca Lush b2b Casska",
    "ROSSY b2b Pauline Herr",
    "Airrica",
    "Alignment",
    "Alyssa Jolee",
    "Angerfist",
    "Angrybaby",
    "ATLiens",
    "Audien",
    "Bad Boombox",
    "Baggi",
    "Black Tiger Sex Machine",
    "Brennan Heart",
    "Chris Lorenzo",
    "Control Freak",
    "Dax J",
    "Deorro",
    "DJ Isaac",
    "DØMINA",
    "Don Jamal",
    "Dual Damage",
    "Eater",
    "Eli Brown",
    "Ely Oaks",
    "Etari",
    "Godlands",
    "Hannah Laing",
    "Hex Cougar",
    "HNTR",
    "J. Worra",
    "Jaden Bojsen",
    "JAWNS",
    "Jessica Audiffred",
    "JEV",
    "John Bryars",
    "Justin Jay",
    "Kayzo",
    "Keenan Mathias",
    "Klangkuenstler",
    "Korolova",
    "LAYZ",
    "MADGRRL",
    "Malóne",
    "Marco Strous",
    "Matroda",
    "mischluft",
    "Mish",
    "Moody Good",
    "Moore Kismet",
    "Nikita the Wicked",
    "Ollie Lishman",
    "ONYVAA",
    "Panteros666",
    "Papa Lu",
    "Pegassi",
    "Ray Volpe",
    "SIDEPIECE",
    "southstar",
    "SPFDJ",
    "The Outlaw",
    "Tiffy Vera",
    "Walker & Royce",
    "Wavedash",
    "Yeong",
    "Zoey808",
  ],
} satisfies Festival;

// Source: search summaries of press.insomniac.com, edmidentity.com, electronicgroove.com,
// edmtunes.com, djlifemag.com (pages couldn't be fetched). ~63 of 80+ artists.
export const escape2026 = {
  id: "escape-2026",
  name: "Escape",
  year: 2026,
  startDate: "2026-10-30",
  location: "San Bernardino, CA",
  dates: "Oct 30–31",
  gradient: "from-orange-400 via-red-500 to-purple-700",
  partial: true,
  lineup: [
    "Zedd",
    "Ice Cube",
    "Excision",
    "Richie Hawtin",
    "Dimitri Vegas & Like Mike",
    "Galantis",
    "Steve Aoki",
    "Benny Benassi",
    "Alok",
    "Morten",
    "Cloonee",
    "Disco Lines",
    "Jamie Jones b2b Franky Rizardo",
    "Joseph Capriati b2b SOSA",
    "Indira Paganotto",
    "Nina Kraviz",
    "Showtek (Hardstyle Set)",
    "Cascada",
    "NERVO",
    "Adventure Club",
    "Liquid Stranger",
    "999999999",
    "AC Slater",
    "Adam Ten",
    "Avalon Emerson",
    "AZYR",
    "Bou",
    "Cera Khin",
    "Clara Cuvé",
    "Dabin",
    "Darren Styles",
    "DJ Heartstring",
    "DJ Tennis",
    "Dr. Fresch",
    "Frontliner (Journey Set)",
    "Funk Assault",
    "Gammer",
    "Getter",
    "Ian Asher",
    "Jon Casey",
    "Joyryde (Sunset Set)",
    "K?d Presents: Kill The Kid",
    "Kai Wachi",
    "Kana Hishiya",
    "KLOUD",
    "KREAM",
    "Lady Faith b2b LNY TNZ",
    "Level Up",
    "Maddix",
    "Malugi",
    "OMNOM",
    "San Pacho",
    "Silvie Loto",
    "TELYKAST",
    "Trancemaster Krause",
    "Trym",
    "YDG",
    "Alex Chapman b2b Zoe Gitter",
    "Andruss b2b Juos",
    "Cat & Maomi",
    "Pedroz",
    "Rommii",
    "Yanamaste",
  ],
} satisfies Festival;

// Source: search summaries of edmidentity.com, musicfestivalwizard.com, globaldanceelectronic.com,
// clashfinder.com set times (pages couldn't be fetched). Believed complete (~68 artists).
export const escape2022 = {
  id: "escape-2022",
  name: "Escape",
  year: 2022,
  startDate: "2022-10-28",
  location: "San Bernardino, CA",
  dates: "Oct 28–29",
  gradient: "from-orange-400 via-red-500 to-purple-700",
  lineup: [
    "Marshmello",
    "Tiësto",
    "Martin Garrix",
    "Eric Prydz",
    "Diplo",
    "Alesso",
    "Subtronics",
    "Oliver Heldens",
    "Black Tiger Sex Machine",
    "Deorro b2b Valentino Khan",
    "Said The Sky",
    "Nina Kraviz",
    "Marco Carola",
    "Vintage Culture",
    "Kayzo",
    "100 gecs",
    "Getter b2b Eptic",
    "Flosstradamus",
    "SIDEPIECE",
    "Bob Moses (Club Set)",
    "Meduza",
    "Deborah De Luca",
    "Ben Klock",
    "ANNA",
    "Eli Brown",
    "Wax Motif",
    "Radical Redemption",
    "Sub Zero Project",
    "D-Sturb b2b Warface",
    "Da Tweekaz",
    "Ben Nicky presents Xtreme",
    "DJ Anime",
    "Lucii",
    "SAYMYNITTI",
    "Moore Kismet",
    "Nurko (Nightfall Set)",
    "Wooli",
    "Modestep",
    "Calcium",
    "The Prototypes",
    "Zingara",
    "Cloonee",
    "Anfisa Letyago",
    "Chris Stussy",
    "HoneyLuv",
    "J. Worra",
    "Brennen Grey",
    "Drakk",
    "Miane",
    "Bones",
    "KLOUD",
    "Florian Picasso",
    "Kill Script",
    "BIJOU",
    "Blossom",
    "KROMI",
    "Dot",
    "Pauline Herr",
    "FrostTop",
    "Shiverz",
    "Skellytn",
    "Sound Rush",
    "Lucky Rabbit",
    "SOREN",
    "Kreation",
  ],
} satisfies Festival;
