import type { Festival } from "@/lib/festivals";

// The Governors Ball (New York). Requested via festival_requests.
// Source: search summaries of brooklynvegan.com set times and lineup posts, uproxx.com, rollingstone.com,
// amny.com, nbcnewyork.com (pages couldn't be fetched). Believed complete; LÉON is billed but unconfirmed.
// Cancelled and left out: Davido (→ Metro Boomin), Omar Apollo (→ Remi Wolf), Tems (→ Ari Lennox).
export const govBall2023 = {
  id: "governors-ball-2023",
  name: "Governors Ball",
  aliases: ["The Governors Ball", "The Governor's Ball", "Governor's Ball", "Gov Ball"],
  year: 2023,
  startDate: "2023-06-09",
  location: "Queens, NY",
  dates: "Jun 9–11",
  gradient: "from-cyan-300 via-sky-400 to-blue-600",
  lineup: [
    "Lizzo",
    "ODESZA",
    "Kendrick Lamar",
    "Lil Uzi Vert",
    "Lil Baby",
    "Lil Nas X",
    "HAIM",
    "Diplo",
    "Kim Petras",
    "Metro Boomin",
    "Ice Spice",
    "Remi Wolf",
    "Eladio Carrión",
    "Joey Bada$$",
    "070 Shake",
    "Tai Verdes",
    "Saba",
    "Alexander 23",
    "PJ Morton",
    "MICHELLE",
    "Maxo Kream",
    "KayCyy",
    "Matt Maltese",
    "Awfbeat",
    "School of Rock Queens",
    "PhatJazz",
    "aespa",
    "Rina Sawayama",
    "Lauv",
    "Oliver Tree",
    "FINNEAS",
    "Kenny Beats",
    "Koffee",
    "Snail Mail",
    "Amber Mark",
    "Syd",
    "Suki Waterhouse",
    "Kennyhoopla",
    "Lovejoy",
    "EVAN GIIA",
    "Sarah Kinsley",
    "flipturn",
    "The Amazons",
    "Zolita",
    "Giveon",
    "SOFI TUKKER",
    "Pusha T",
    "girl in red",
    "Central Cee",
    "Ari Lennox",
    "PinkPantheress",
    "black midi",
    "Sabrina Claudio",
    "LÉON",
    "Phony Ppl",
    "Cat Burns",
    "Maude Latour",
    "Coast Contra",
    "Charlie Burg",
    "Ella Jane",
    "Haiku Hands",
    "School of Rock Brooklyn",
  ],
} satisfies Festival;
