import type { Festival } from "@/lib/festivals";

// Lightning in a Bottle (Do LaB, Buena Vista Lake, Bakersfield). Source: search summaries of
// liveforlivemusic.com, edm.com, billboard.com, variety.com, jambase.com, edmidentity.com
// (pages couldn't be fetched). Headliners and announced names; smaller stages are mostly missing.

const GRADIENT = "from-lime-300 via-emerald-400 to-teal-500";

export const lightning2022 = {
  id: "lightning-in-a-bottle-2022",
  name: "Lightning in a Bottle",
  year: 2022,
  startDate: "2022-05-25",
  location: "Bakersfield, CA",
  dates: "May 25–30",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Glass Animals",
    "Kaytranada",
    "GRiZ",
    "Chet Faker",
    "SG Lewis",
    "Purity Ring",
    "Little Simz",
    "Monolink",
    "Lastlings",
    "Moontricks",
    "CHIKA",
    "Empress Of",
    "Rexx Life Raj",
    "Elder Island",
    "Blu DeTiger",
    "Austin Millz",
    "Gone Gone Beyond",
    "Hermanos Gutiérrez",
    "Muzi",
    "Big Wild",
    "GoldLink",
    "Koffee",
    "Ekali",
    "CloZee",
    "G Jones b2b EPROM",
    "Ivy Lab",
    "LSDREAM",
    "Of The Trees",
    "Rome in Silver",
    "Opiuo",
    "Dirtwire",
    "Big Freedia",
    "Elephant Heart",
    "Mr. Carmack",
    "Black Coffee",
    "Four Tet",
    "Seth Troxler",
    "Jon Hopkins",
    "Maya Jane Coles",
    "Sama' Abdulhadi",
    "Hernan Cattaneo",
    "Yotto",
    "Kyle Watson",
    "Eli & Fur",
    "Max Cooper",
    "VNSSA",
    "SOHMI",
    "Paraleven",
    "HoneyLuv",
    "An-Ten-Nae",
    "The Gaslamp Killer",
    "Mimosa",
    "Morillo",
    "GREAZUS",
    "Pressha",
    "SPEKt1",
    "HoneyBee",
    "Henry Pope",
    "Rachel Torro",
    "Dead-Tones",
    "Big Cee",
    "Roxy Venus",
    "G-Dubbs",
    "Mr. Bootsauce",
    "Patricio",
    "Evan Hatfield",
  ],
} satisfies Festival;

export const lightning2023 = {
  id: "lightning-in-a-bottle-2023",
  name: "Lightning in a Bottle",
  year: 2023,
  startDate: "2023-05-24",
  location: "Bakersfield, CA",
  dates: "May 24–29",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Diplo",
    "070 Shake",
    "SOFI TUKKER",
    "ZHU",
    "REZZ",
    "Tale Of Us",
    "Phantogram",
    "Tobe Nwigwe",
    "Caribou",
    "Sampa the Great",
    "TOKiMONSTA",
    "Purple Disco Machine",
    "Beats Antique",
    "Mindchatter",
    "DRAMA",
    "Ozomatli with Chali 2na and Cut Chemist",
    "Liquid Stranger",
    "LSDREAM",
    "Deathpact",
    "The Glitch Mob",
    "LTJ Bukem with MC Armanni",
    "Prospa",
    "Moore Kismet",
    "Wreckno",
    "UNIIQU3",
    "MEUTE",
    "BLOND:ISH",
    "Stephan Bodzin",
    "LP Giobbi",
    "Ben Böhmer",
    "Giorgia Angiuli",
    "TSHA",
    "Cassian",
    "Logic1000",
    "Rinzen",
    "Mary Droppinz",
    "Baby Weight",
    "Shawni",
  ],
} satisfies Festival;

export const lightning2024 = {
  id: "lightning-in-a-bottle-2024",
  name: "Lightning in a Bottle",
  year: 2024,
  startDate: "2024-05-22",
  location: "Bakersfield, CA",
  dates: "May 22–27",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Skrillex",
    "Labrinth",
    "James Blake",
    "M.I.A.",
    "Fatboy Slim",
    "Lane 8",
    "CloZee",
    "ISOxo",
    "Nora En Pure",
    "Tipper",
    "Cannons",
    "Bomba Estéreo",
    "Honey Dijon",
    "Damian Lazarus",
    "Mura Masa",
    "Of The Trees",
    "Floating Points",
    "Overmono",
    "Barclay Crenshaw",
    "Nia Archives",
    "Jyoty",
    "ANNA b2b Sama' Abdulhadi",
    "Justin Martin",
    "Aluna",
    "it's murph",
    "Qveen Herby",
    "Skream (Dubstep Set)",
    "Tycho (Sunset Set)",
    "Bob Moses (Club Set)",
    "Maddy O'Neal",
  ],
} satisfies Festival;

export const lightning2025 = {
  id: "lightning-in-a-bottle-2025",
  name: "Lightning in a Bottle",
  year: 2025,
  startDate: "2025-05-21",
  location: "Bakersfield, CA",
  dates: "May 21–25",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Jamie xx",
    "Khruangbin",
    "Four Tet",
    "John Summit",
    "Channel Tres",
    "Claude VonStroke",
    "Sammy Virji",
    "Subtronics",
    "Shygirl presents Club Shy",
    "Underworld",
    "Magdalena Bay",
    "Amaarae",
    "Tinlicker",
    "Brijean",
    "Audrey Nuna",
    "Priya Ragu",
    "salute",
    "Joy Orbison",
    "Flowdan",
    "TroyBoi",
    "Tape B",
    "PEEKABOO",
    "Francis Mercier",
    "Hamdi",
  ],
} satisfies Festival;

export const lightning2026 = {
  id: "lightning-in-a-bottle-2026",
  name: "Lightning in a Bottle",
  year: 2026,
  startDate: "2026-05-20",
  location: "Bakersfield, CA",
  dates: "May 20–24",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Empire of the Sun",
    "Zeds Dead",
    "Mau P",
    "Sara Landry",
    "Chase & Status",
    "Mochakk",
    "Barry Can't Swim",
    "Tinashe",
    "Of The Trees",
    "Dimension",
    "Overmono",
    "Daily Bread",
    "ALLEYCVT",
    "INZO",
    "Nia Archives",
    "DJ Trixie Mattel",
    "Jayda G",
    "Lee Burridge",
    "Maceo Plex",
    "Hot Since 82",
    "Desert Hearts (Mikey Lion, Lee Reynolds, Marbs)",
    "Linska",
    "GiZ",
    "Cquestt's Baile World",
    "Ksenyeah b2b Manguito",
    "DJ Heartstring",
    "MPH",
    "Flava D",
    "Effy",
    "Sarz",
    "borne",
    "CASEY CLUB",
    "EREZ",
    "Mindex",
    "Bass Temple",
    "Donna Dada",
    "AMIRA",
    "Respect DnB",
    "Worra",
    "Marsh",
    "Main Phase",
    "Brunello",
    "Elephant Heart",
    "Madam X",
    "Justin Hawkes",
    "RICHE",
    "RM47",
    "Bianca Maieli",
    "Clearcast",
    "Cocoa Crescendo",
  ],
} satisfies Festival;
