import type { Festival } from "@/lib/festivals";

// Lollapalooza Chicago (Grant Park). Source: search summaries of nbcchicago.com, abc7chicago.com,
// brooklynvegan.com, cbsnews.com, billboard.com, timeout.com (pages couldn't be fetched).
// ~170 artists a year; these lists cover the headliners and bigger names.

const GRADIENT = "from-yellow-300 via-lime-400 to-cyan-500";

// Doja Cat dropped out (replaced by J-Hope), so she isn't listed.
export const lollapalooza2022 = {
  id: "lollapalooza-2022",
  name: "Lollapalooza",
  year: 2022,
  startDate: "2022-07-28",
  location: "Chicago, IL",
  dates: "Jul 28–31",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Metallica",
    "Dua Lipa",
    "J. Cole",
    "Green Day",
    "J-Hope",
    "Lil Baby",
    "Machine Gun Kelly",
    "Kygo",
    "Jane's Addiction",
    "The Kid LAROI",
    "Charli XCX",
    "Glass Animals",
    "Big Sean",
    "Don Toliver",
    "Jazmine Sullivan",
    "Kaskade",
    "Billy Strings",
    "ZHU",
    "REZZ",
    "Idles",
    "Turnstile",
    "Denzel Curry",
    "Måneskin",
    "TOMORROW X TOGETHER",
    "100 gecs",
    "Still Woozy",
    "Ashnikko",
    "Black Coffee",
    "Manchester Orchestra",
    "Tove Lo",
    "Caroline Polachek",
    "MK",
    "Remi Wolf",
    "Zach Bryan",
    "PinkPantheress",
    "Chris Lorenzo",
    "Role Model",
    "Inhaler",
    "Sam Fender",
    "King Princess",
    "girl in red",
    "Liquid Stranger",
    "CloZee",
    "Royal Blood",
    "Cordae",
    "Bob Moses",
    "Coi Leray",
    "Tinashe",
    "MUNA",
    "Wet Leg",
    "Glaive",
    "SoFaygo",
    "The Regrettes",
    "LP Giobbi",
    "Whipped Cream",
    "Wallows",
    "YG",
    "GLXST",
    "Duke Dumont",
    "WILLOW",
    "Chelsea Cutler",
    "COIN",
    "FLETCHER",
    "SIDEPIECE",
    "Dashboard Confessional",
    "Larry June",
    "Gracie Abrams",
    "Jax Jones",
    "Griff",
    "Mariah the Scientist",
    "GAYLE",
    "Local Natives",
    "Beach Bunny",
    "Young Nudy",
    "Kennyhoopla",
    "Teezo Touchdown",
    "Horsegirl",
  ],
} satisfies Festival;

// Only the headliners and larger names could be confirmed for this year.
export const lollapalooza2023 = {
  id: "lollapalooza-2023",
  name: "Lollapalooza",
  year: 2023,
  startDate: "2023-08-03",
  location: "Chicago, IL",
  dates: "Aug 3–6",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Billie Eilish",
    "Kendrick Lamar",
    "Red Hot Chili Peppers",
    "Lana Del Rey",
    "Karol G",
    "The 1975",
    "ODESZA",
    "TOMORROW X TOGETHER",
    "Fred again..",
    "Thirty Seconds to Mars",
    "Noah Kahan",
    "Carly Rae Jepsen",
    "Diplo",
    "NewJeans",
    "Portugal. The Man",
    "Subtronics",
    "Tems",
    "Maggie Rogers",
    "JID",
    "Pusha T",
    "Yung Gravy",
    "The Revivalists",
    "Suki Waterhouse",
    "A Boogie Wit da Hoodie",
    "Louis The Child",
    "Rina Sawayama",
    "Lil Yachty",
  ],
} satisfies Festival;

// Tyler, The Creator cancelled (replaced by Megan Thee Stallion), so he isn't listed.
export const lollapalooza2024 = {
  id: "lollapalooza-2024",
  name: "Lollapalooza",
  year: 2024,
  startDate: "2024-08-01",
  location: "Chicago, IL",
  dates: "Aug 1–4",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "SZA",
    "Megan Thee Stallion",
    "Hozier",
    "Stray Kids",
    "The Killers",
    "Future x Metro Boomin",
    "blink-182",
    "Melanie Martinez",
    "Skrillex",
    "Jungle",
    "Kesha",
    "Chappell Roan",
    "d4vd",
    "Tyla",
    "Daði Freyr",
    "The Japanese House",
    "FLO",
    "Olivia Dean",
    "Fleshwater",
    "Blondshell",
    "Faye Webster",
    "Sexyy Red",
    "Kevin Abstract",
    "Militarie Gun",
    "Geese",
    "Deftones",
    "Killer Mike",
    "TV Girl",
    "Four Tet",
    "Ethel Cain",
    "Kenny Beats",
    "Romy",
    "Eyedress",
    "Dora Jar",
    "Nia Archives",
    "Friko",
    "Vince Staples",
    "The Last Dinner Party",
    "Cults",
    "Slow Pulp",
  ],
} satisfies Festival;

export const lollapalooza2025 = {
  id: "lollapalooza-2025",
  name: "Lollapalooza",
  year: 2025,
  startDate: "2025-07-31",
  location: "Chicago, IL",
  dates: "Jul 31–Aug 3",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Sabrina Carpenter",
    "Olivia Rodrigo",
    "Tyler, The Creator",
    "Luke Combs",
    "RÜFÜS DU SOL",
    "TWICE",
    "A$AP Rocky",
    "Korn",
    "Gracie Abrams",
    "Doechii",
    "Clairo",
    "Young Miko",
    "Mk.gee",
    "MARINA",
    "JPEGMAFIA",
    "Djo",
    "Bleachers",
    "T-Pain",
    "Foster the People",
    "Bladee",
    "Amaarae",
    "The Dare",
    "Ravyn Lenae",
    "Otoboke Beaver",
    "Orla Gartland",
    "Jane Remover",
    "Caroline Kingsbury",
    "Dom Dolla",
    "Sierra Ferrell",
    "Cage the Elephant",
    "Royel Otis",
    "Magdalena Bay",
    "Overmono",
    "The Blessed Madonna",
    "Fcukers",
    "julie",
    "Ratboys",
    "Nourished by Time",
    "Sunami",
    "Xaviersobased",
    "Bôa",
    "Dua Saleh",
    "Winnetka Bowling League",
    "Rachel Grae",
    "Dominic Fike",
    "FINNEAS",
    "Remi Wolf",
    "The Marías",
    "Isaiah Rashad",
    "Mariah the Scientist",
    "Artemas",
    "La Femme",
    "Rebecca Black",
  ],
} satisfies Festival;

// Saturday was delayed by flooding; some early sets were cancelled. Lil Uzi Vert cancelled.
export const lollapalooza2026 = {
  id: "lollapalooza-2026",
  name: "Lollapalooza",
  year: 2026,
  startDate: "2026-07-30",
  location: "Chicago, IL",
  dates: "Jul 30–Aug 2",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Charli xcx",
    "Tate McRae",
    "Lorde",
    "Olivia Dean",
    "John Summit",
    "JENNIE",
    "The Smashing Pumpkins",
    "The xx",
    "Turnstile",
    "sombr",
    "The Neighbourhood",
    "YUNGBLUD",
    "beabadoobee",
    "Ethel Cain",
    "Empire of the Sun",
    "Major Lazer",
    "Zara Larsson",
    "The Chainsmokers",
    "aespa",
    "YOASOBI",
    "Ado",
    "Clipse",
    "Geese",
    "Wolf Alice",
    "CORTIS",
    "Little Simz",
    "5 Seconds of Summer",
    "Wet Leg",
    "Blood Orange",
    "WORSHIP",
    "KETTAMA",
    "Viagra Boys",
    "Audrey Hobert",
    "Snow Strippers",
    "Boris Brejcha",
    "Paris Paloma",
    "CMAT",
    "Boys Noize",
    "Between Friends",
    "Freddie Gibbs",
    "The Story So Far",
    "i-dle",
    "PartyOf2",
    "High Vis",
    "Slayyyter",
    "Disco Lines",
    "Leon Thomas",
    "Alison Wonderland",
    "DJ Trixie Mattel",
    "bbno$",
    "kwn",
    "Sienna Spiro",
    "Max Styler",
    "Spacey Jane",
    "Whethan",
    "MUNA",
    "Hot Mulligan",
    "JADE",
    "Eli Brown",
    "Duke Dumont",
  ],
} satisfies Festival;
