import type { Festival } from "@/lib/festivals";

// 2022–2025 source: search summaries of pastemagazine.com, riffmagazine.com, brooklynvegan.com,
// kqed.org, goodmorningamerica.com, edmidentity.com (SOMA tent) — pages couldn't be fetched.

export const outsideLands2022 = {
  id: "outside-lands-2022",
  name: "Outside Lands",
  year: 2022,
  startDate: "2022-08-05",
  location: "San Francisco, CA",
  dates: "Aug 5–7",
  gradient: "from-amber-300 via-orange-500 to-rose-600",
  partial: true,
  lineup: [
    "Green Day",
    "Post Malone",
    "SZA",
    "Jack Harlow",
    "Weezer",
    "Phoebe Bridgers",
    "ILLENIUM",
    "Lil Uzi Vert",
    "Kali Uchis",
    "Disclosure",
    "Mitski",
    "Polo & Pan",
    "Anitta",
    "Dominic Fike",
    "Oliver Tree",
    "Mac DeMarco",
    "Pusha T",
    "Mt. Joy",
    "Kim Petras",
    "Local Natives",
    "The Marías",
    "Larry June",
    "100 gecs",
    "Parcels",
    "Dayglow",
    "Purple Disco Machine",
    "Hiatus Kaiyote",
    "Washed Out",
    "Ashe",
    "Surf Mesa",
    "Wet Leg",
    "Sam Fender",
    "Role Model",
    "Baby Tate",
    "The Backseat Lovers",
    "Amber Mark",
    "Best Coast",
    "Franc Moody",
    "Pussy Riot",
    "Duckwrth",
    "Empress Of",
    "Rostam",
    "Zoe Wees",
    "Faye Webster",
    "Griff",
    "Anna Lunoe",
    "Kennyhoopla",
    "Maxo Kream",
    "Lido Pimienta",
    "Briston Maroney",
    "Sampa the Great",
    "Del Water Gap",
    "Robert Glasper",
    "Inner Wave",
    "Tyla Yaweh",
    "Glaive",
    "The Beths",
    "Petey",
    "Odie",
    "Benny Sings",
    "Thuy",
    "MICHELLE",
    "Jelani Aryeh",
    "Claude VonStroke",
    "Dixon",
    "TOKiMONSTA",
    "ANNA",
    "Avalon Emerson",
    "J. Worra",
    "Major League DJz",
    "AMÉMÉ",
    "Ellen Allien",
    "ABSOLUTE.",
    "Cassian",
    "DJ Minx",
    "DJ Seinfeld",
    "JOPLYN",
    "Perel",
  ],
} satisfies Festival;

export const outsideLands2023 = {
  id: "outside-lands-2023",
  name: "Outside Lands",
  year: 2023,
  startDate: "2023-08-11",
  location: "San Francisco, CA",
  dates: "Aug 11–13",
  gradient: "from-amber-300 via-orange-500 to-rose-600",
  partial: true,
  lineup: [
    "Kendrick Lamar",
    "Foo Fighters",
    "ODESZA",
    "Lana Del Rey",
    "The 1975",
    "Megan Thee Stallion",
    "Zedd",
    "Janelle Monáe",
    "Maggie Rogers",
    "FISHER",
    "JID",
    "Lil Yachty",
    "Noah Kahan",
    "Cigarettes After Sex",
    "Interpol",
    "WILLOW",
    "Father John Misty",
    "Tobe Nwigwe",
    "Orville Peck",
    "aespa",
    "Cuco",
    "Alex G",
    "Claptone",
    "Monolink",
    "DIESEL (Shaquille O'Neal)",
    "Raveena",
    "BLOND:ISH",
    "Becky Hill",
    "Crumb",
    "Justin Jay",
    "Ethel Cain",
    "The Dip",
    "Samia",
    "Disco Lines",
    "La Doña",
    "Yaya Bey",
    "Nation of Language",
    "Evan Giia",
    "Matt Hansen",
    "Westend",
    "Nala",
    "Miss Dre",
    "Izzy Heltai",
    "L'Impératrice",
    "Nora En Pure",
    "Alvvays",
    "NIKI",
    "Mariah the Scientist",
    "Trixie Mattel",
    "Daniel Avery",
    "Lovejoy",
    "Sama' Abdulhadi",
    "Jessie Murph",
    "Zack Fox",
    "Denis Sulta",
    "Cobra Man",
    "TOPS",
    "Orion Sun",
    "VNSSA",
    "manila grey",
    "Donny Benét",
    "Eddie Zuko",
    "Kim Ann Foxman",
    "No Vacation",
    "Wednesday",
    "midwxst",
    "Adi Oasis",
    "EREZ",
    "Sour Widows",
    "beabadoobee",
    "Poolside",
    "Soccer Mommy",
    "ISOxo",
    "Holly Humberstone",
    "Âme b2b Trikk",
    "WhoMadeWho",
    "Joy Oladokun",
    "Inhaler",
    "Tinlicker",
    "DOPE LEMON",
    "Gabriels",
    "The Jungle Giants",
    "Mild Minds",
    "Red Axes",
    "Nanna",
    "Coco & Breezy",
    "Wild Child",
    "UPSAHL",
    "Pretty Sick",
    "Grace Ives",
    "Fake Fruit",
    "Loverground",
    "Venus & the Flytraps",
  ],
} satisfies Festival;

// Tyler, The Creator was announced but didn't play; Sabrina Carpenter replaced him.
export const outsideLands2024 = {
  id: "outside-lands-2024",
  name: "Outside Lands",
  year: 2024,
  startDate: "2024-08-09",
  location: "San Francisco, CA",
  dates: "Aug 9–11",
  gradient: "from-amber-300 via-orange-500 to-rose-600",
  partial: true,
  lineup: [
    "The Killers",
    "Sabrina Carpenter",
    "Sturgill Simpson",
    "Post Malone",
    "The Postal Service",
    "Grace Jones",
    "Daniel Caesar",
    "Jungle",
    "Kaytranada",
    "Victoria Monét",
    "Chappell Roan",
    "Reneé Rapp",
    "Teddy Swims",
    "Gryffin",
    "Young the Giant",
    "Tyla",
    "ScHoolboy Q",
    "Chris Lake",
    "Snoh Aalegra",
    "Slowdive",
    "Killer Mike",
    "Idris Elba",
    "Channel Tres",
    "Charley Crockett",
    "Men I Trust",
    "Amyl and the Sniffers",
    "The Blessed Madonna",
    "Romy",
    "STRFKR",
    "Sofia Kourtesis",
    "K.Flay",
    "Leisure",
    "Mimi Webb",
    "Binki",
    "Lady Wray",
    "French Cassettes",
    "Kevin Abstract",
    "The Japanese House",
    "The Last Dinner Party",
    "Real Estate",
    "Daði Freyr",
    "billy woods",
    "The Lemon Twigs",
    "SIDEPIECE",
    "Mindchatter",
    "Rochelle Jordan",
    "Jackie Hollander",
    "TV Girl",
    "Paul Cauthen",
    "BADBADNOTGOOD",
    "Amen Dunes",
    "Ben Howard",
    "Corinne Bailey Rae",
    "Wisp",
    "CMAT",
    "Cimafunk",
    "Katie Pruitt",
    "Lael Neale",
    "Dan Spencer",
  ],
} satisfies Festival;

export const outsideLands2025 = {
  id: "outside-lands-2025",
  name: "Outside Lands",
  year: 2025,
  startDate: "2025-08-08",
  location: "San Francisco, CA",
  dates: "Aug 8–10",
  gradient: "from-amber-300 via-orange-500 to-rose-600",
  partial: true,
  lineup: [
    "Tyler, The Creator",
    "Hozier",
    "Doja Cat",
    "Vampire Weekend",
    "Anderson .Paak & The Free Nationals",
    "Glass Animals",
    "Jamie xx",
    "Doechii",
    "John Summit",
    "Gracie Abrams",
    "Bleachers",
    "Gesaffelstein",
    "Ludacris",
    "Jorja Smith",
    "Beck",
    "Still Woozy",
    "Thundercat",
    "MARINA",
    "Wallows",
    "Royel Otis",
    "Black Coffee",
    "Sammy Virji",
    "FINNEAS",
    "ARMNHMR",
    "Role Model",
    "Floating Points",
    "Fujii Kaze",
    "BUNT.",
    "DJ Koze",
    "Mark Ambor",
    "Jessica Pratt",
    "Mannequin Pussy",
    "Notion",
    "Fcukers",
    "Vansire",
    "nimino",
    "Destroy Boys",
    "INJI",
    "ATRIP",
    "Midrift",
    "Baalti",
    "almost monday",
    "Alexandra Savior",
    "NewDad",
    "Alemeda",
    "Avatari",
    "Chase Icon",
    "Memphy",
    "Dangerous Rose",
    "Adam Kraft",
    "Beverly Chills",
    "Just Another Bitch",
    "MAMA SAN",
    "Artemas",
    "Claude VonStroke",
    "Bakar",
    "flipturn",
    "2hollis",
    "Walker & Royce",
    "Dombresky",
    "LaRussell",
    "Girl Math",
    "VNSSA",
    "Nala",
    "DJ Pee .Wee",
    "Wasia Project",
    "Klangphonics",
    "Kate Bollinger",
    "Sarah Kinsley",
    "Matt Champion",
    "Wunderhorse",
    "Amelia Moore",
    "Paco Versailles",
    "Good Neighbours",
    "Bay Ledges",
    "DJ Mandy",
    "BigXthaPlug",
    "Levity",
    "BLOND:ISH",
    "Claptone",
    "Rebecca Black",
    "CA7RIEL & Paco Amoroso",
    "julie",
    "Mayer Hawthorne",
    "Big Freedia",
    "San Francisco Gay Men's Chorus",
    "Hope Tala",
    "Luna Li",
    "&friends",
    "Naomi Sharon",
    "Neal Francis",
    "Lexa Gates",
    "TxC",
    "Orla Gartland",
    "Arcy Drive",
    "Nourished by Time",
    "bLAck pARty",
    "Midnight Generation",
    "Alex Amen",
    "Banksia",
    "Father Figure",
    "David Harness",
    "Jen DM",
    "Chelsea Starr",
    "Mouthfeel",
  ],
} satisfies Festival;

// Source: search summaries of jambase.com, sfchronicle.com, consequence.net, brooklynvegan.com,
// edmidentity.com, sfoutsidelands.com (pages couldn't be fetched). ~96 artists.
export const outsideLands2026 = {
  id: "outside-lands-2026",
  name: "Outside Lands",
  year: 2026,
  startDate: "2026-08-07",
  location: "San Francisco, CA",
  dates: "Aug 7–9",
  gradient: "from-amber-300 via-orange-500 to-rose-600",
  partial: true,
  lineup: [
    "Charli xcx",
    "The Strokes",
    "RÜFÜS DU SOL",
    "The xx",
    "Baby Keem",
    "Turnstile",
    "GRiZTRONICS",
    "Djo",
    "Labrinth",
    "Empire of the Sun",
    "Dijon",
    "PinkPantheress",
    "GloRilla",
    "Clipse",
    "Death Cab for Cutie",
    "Modest Mouse",
    "Ethel Cain",
    "Lucy Dacus",
    "Geese",
    "Wet Leg",
    "Tinashe",
    "Mariah the Scientist",
    "Sierra Ferrell",
    "Boys Noize",
    "Lane 8",
    "Boris Brejcha",
    "Ben Böhmer",
    "Tycho",
    "The Temper Trap",
    "JADE",
    "The Story So Far",
    "Yard Act",
    "Malcolm Todd",
    "Snow Strippers",
    "Audrey Hobert",
    "Trixie Mattel",
    "HYPERBEAM (Odd Mob & OMNOM)",
    "¥ØU$UK€ ¥UK1MAT$U",
    "KI/KI",
    "Sultan + Shepard",
    "Disco Lines",
    "Miss Monique",
    "Carlita",
    "MPH",
    "ALLEYCVT",
    "Kerala Dust",
    "Etari",
    "Grace Ives",
    "Dylan Brady",
    "Durand Bernarr",
    "Die Spitz",
    "Goldie Boutilier",
    "Tobiahs",
    "Billie Marten",
    "Faouzia",
    "Bad Nerves",
    "Luke Alessi",
    "Chezile",
    "Sawyer Hill",
    "Nezza",
    "Vertigo",
    "it's murph",
    "Łaszewo",
    "Sienna Spiro",
    "Silvana Estrada",
    "Haute & Freddy",
    "Wunderhorse",
    "camoufly",
    "Bandalos Chinos",
    "After",
    "Rio Kosta",
    "Automatic",
    "Racing Mount Pleasant",
    "Bad Juuju",
    "1-800 GIRLS",
    "Red Leather",
    "RYMAN",
    "Not for Radio",
    "kwn",
    "Destin Conrad",
    "Kingfishr",
    "Balu Brigada",
    "Frost Children",
    "Amble",
    "Momma",
    "Infinity Song",
    "Sports",
    "Marlon Funaki",
    "Night Tapes",
    "X CLUB",
    "Jim Legxacy",
    "sosocamo",
    "Day We Ran",
    "Cruz Beckham",
    "Britton",
    "San Francisco Gay Men's Chorus",
  ],
} satisfies Festival;
