import type { Festival } from "@/lib/festivals";

// Source: search summaries of jambase.com, sfchronicle.com, consequence.net, brooklynvegan.com,
// edmidentity.com, sfoutsidelands.com (pages couldn't be fetched). ~96 artists.
export const outsideLands2026 = {
  id: "outside-lands-2026",
  name: "Outside Lands",
  year: 2026,
  startDate: "2026-08-07",
  location: "San Francisco, CA",
  dates: "Aug 7–9",
  gradient: "from-amber-300 via-orange-500 to-rose-600",
  partial: true,
  lineup: [
    "Charli xcx",
    "The Strokes",
    "RÜFÜS DU SOL",
    "The xx",
    "Baby Keem",
    "Turnstile",
    "GRiZTRONICS",
    "Djo",
    "Labrinth",
    "Empire of the Sun",
    "Dijon",
    "PinkPantheress",
    "GloRilla",
    "Clipse",
    "Death Cab for Cutie",
    "Modest Mouse",
    "Ethel Cain",
    "Lucy Dacus",
    "Geese",
    "Wet Leg",
    "Tinashe",
    "Mariah the Scientist",
    "Sierra Ferrell",
    "Boys Noize",
    "Lane 8",
    "Boris Brejcha",
    "Ben Böhmer",
    "Tycho",
    "The Temper Trap",
    "JADE",
    "The Story So Far",
    "Yard Act",
    "Malcolm Todd",
    "Snow Strippers",
    "Audrey Hobert",
    "Trixie Mattel",
    "HYPERBEAM (Odd Mob & OMNOM)",
    "¥ØU$UK€ ¥UK1MAT$U",
    "KI/KI",
    "Sultan + Shepard",
    "Disco Lines",
    "Miss Monique",
    "Carlita",
    "MPH",
    "ALLEYCVT",
    "Kerala Dust",
    "Etari",
    "Grace Ives",
    "Dylan Brady",
    "Durand Bernarr",
    "Die Spitz",
    "Goldie Boutilier",
    "Tobiahs",
    "Billie Marten",
    "Faouzia",
    "Bad Nerves",
    "Luke Alessi",
    "Chezile",
    "Sawyer Hill",
    "Nezza",
    "Vertigo",
    "it's murph",
    "Łaszewo",
    "Sienna Spiro",
    "Silvana Estrada",
    "Haute & Freddy",
    "Wunderhorse",
    "camoufly",
    "Bandalos Chinos",
    "After",
    "Rio Kosta",
    "Automatic",
    "Racing Mount Pleasant",
    "Bad Juuju",
    "1-800 GIRLS",
    "Red Leather",
    "RYMAN",
    "Not for Radio",
    "kwn",
    "Destin Conrad",
    "Kingfishr",
    "Balu Brigada",
    "Frost Children",
    "Amble",
    "Momma",
    "Infinity Song",
    "Sports",
    "Marlon Funaki",
    "Night Tapes",
    "X CLUB",
    "Jim Legxacy",
    "sosocamo",
    "Day We Ran",
    "Cruz Beckham",
    "Britton",
    "San Francisco Gay Men's Chorus",
  ],
} satisfies Festival;
