import type { Festival } from "@/lib/festivals";

// Portola (Goldenvoice, Pier 80, San Francisco). Source: search summaries of jambase.com, edmidentity.com,
// edm.com, grooveist.com, consequence.net, brooklynvegan.com, gvwire.com (pages couldn't be fetched).

const GRADIENT = "from-cyan-300 via-sky-400 to-blue-600";

// M.I.A. pulled out the day before; Oneohtrix Point Never replaced her.
export const portola2022 = {
  id: "portola-2022",
  name: "Portola",
  year: 2022,
  startDate: "2022-09-24",
  location: "San Francisco, CA",
  dates: "Sep 24–25",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Flume",
    "The Chemical Brothers",
    "James Blake",
    "Kaytranada",
    "Jamie xx",
    "Jungle",
    "Charli XCX",
    "Fatboy Slim",
    "Lane 8",
    "Peggy Gou",
    "Gorgon City",
    "Fred again..",
    "Caroline Polachek",
    "Caribou",
    "Omar Apollo",
    "Bicep",
    "The Avalanches",
    "Arca",
    "PinkPantheress",
    "Hot Since 82",
    "Justin Martin",
    "Romy",
    "Ross From Friends",
    "NEIL FRANCES",
    "Giolì & Assia",
    "TSHA",
    "Sad Night Dynamite",
    "George Fitzgerald",
    "DJ Holographic",
    "Godford",
    "Elkka",
    "Young Franco",
    "jamesjamesjames",
    "Dials",
    "Toro y Moi",
    "Four Tet",
    "Floating Points",
    "SG Lewis",
    "Duke Dumont",
    "Yaeji",
    "The Blessed Madonna",
    "L'Impératrice",
    "Yves Tumor",
    "slowthai",
    "Keinemusik",
    "&ME",
    "Rampa",
    "Adam Port",
    "Palace",
    "Kelly Lee Owens",
    "Shygirl",
    "Slayyyter",
    "Danilo Plessow",
    "Sofia Kourtesis",
    "HAAi",
    "Ela Minus",
    "Dawn Richard",
    "Prospa",
    "Ama",
    "DJ_Dave",
    "The Range",
    "Eug",
    "Maddy Maia",
    "Tottie",
    "Oneohtrix Point Never",
  ],
} satisfies Festival;

export const portola2023 = {
  id: "portola-2023",
  name: "Portola",
  year: 2023,
  startDate: "2023-09-30",
  location: "San Francisco, CA",
  dates: "Sep 30–Oct 1",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Skrillex",
    "Eric Prydz",
    "Labrinth",
    "Polo & Pan",
    "FKJ",
    "Nelly Furtado",
    "Jai Paul",
    "Underworld",
    "Major Lazer",
    "Thundercat",
    "Rina Sawayama",
    "Carl Cox",
    "Charlotte de Witte",
    "Major League DJz",
    "Purple Disco Machine",
    "Dom Dolla",
    "Hot Chip",
    "Chromeo",
    "Tokischa",
    "Flying Lotus",
    "SBTRKT",
    "DJ Koze",
    "Jon Hopkins",
    "Overmono",
    "TEED",
    "Young Fathers",
    "Two Shell",
    "The Dare",
    "salute",
    "Barry Can't Swim",
    "Eliza Rose",
    "Model/Actriz",
    "LF SYSTEM",
    "ELIO",
    "Maddy Maia",
    "Chris Lake b2b Armand Van Helden",
    "The Blaze",
    "Bonobo",
    "Masego",
    "Basement Jaxx",
    "Little Dragon",
    "Kenny Beats",
    "Little Simz",
    "Todd Terje",
    "Róisín Murphy",
    "2manydjs",
    "Kavinsky",
    "Pabllo Vittar",
    "Jockstrap",
    "COBRAH",
    "Avalon Emerson",
    "Jayda G",
    "Sam Gellaitry",
    "Skin On Skin",
    "Chaos in The CBD",
    "yeule",
    "Jyoty",
    "Yung Singh",
    "Winston Surfshirt",
    "Azzecca",
    "Very Nice Person",
  ],
} satisfies Festival;

export const portola2024 = {
  id: "portola-2024",
  name: "Portola",
  year: 2024,
  startDate: "2024-09-28",
  location: "San Francisco, CA",
  dates: "Sep 28–29",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "RÜFÜS DU SOL",
    "Gesaffelstein",
    "Four Tet",
    "Jamie xx",
    "Justice",
    "Disclosure",
    "FISHER",
    "M.I.A.",
    "A. G. Cook",
    "AHADADREAM",
    "Barry Can't Swim",
    "Ben Böhmer",
    "Bicep presents Chroma (AV DJ Set)",
    "Boys Noize b2b VTSS",
    "Busy P b2b Braxe + Falcon",
    "Carlita b2b DJ Tennis",
    "Chase & Status",
    "Deltron 3030",
    "DJ Heartstring",
    "DJ Pee .Wee",
    "DJ Seinfeld",
    "Empress Of",
    "Fcukers",
    "Floating Points",
    "Franc Moody",
    "Glass Beams",
    "Honey Dijon",
    "horsegiirL",
    "Interplanetary Criminal",
    "Jasper Tygner",
    "Jersey",
    "Jessie Ware",
    "Joy Orbison",
    "JPEGMAFIA",
    "Lava La Rue",
    "LP Giobbi",
    "Luke Alessi",
    "Maddy Maia",
    "Mall Grab",
    "Mochakk",
    "Mount Kimbie",
    "Nala",
    "NEIL FRANCES",
    "Nia Archives",
    "Nils Hoffmann",
    "Nooriyah",
    "Panjabi Hit Squad",
    "Peaches",
    "Pretty Girl",
    "Raf Saperra",
    "Rebecca Black",
    "Sammy Virji",
    "Sara Landry",
    "Shygirl presents Club Shy",
    "Snow Strippers",
    "Soulwax",
    "STARRZA",
    "Tinlicker",
    "Tycho",
    "ZULAN",
    "Kenya Grace",
    "Astra Club",
  ],
} satisfies Festival;

// Anti Up = Chris Lake & Chris Lorenzo.
export const portola2025 = {
  id: "portola-2025",
  name: "Portola",
  year: 2025,
  startDate: "2025-09-20",
  location: "San Francisco, CA",
  dates: "Sep 20–21",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "LCD Soundsystem",
    "Christina Aguilera",
    "The Chemical Brothers",
    "Moby",
    "The Prodigy",
    "Peggy Gou",
    "Dom Dolla",
    "Underworld",
    "Blood Orange",
    "Caribou",
    "Anti Up",
    "Mau P",
    "The Rapture",
    "Arca",
    "Duke Dumont",
    "2manydjs b2b Erol Alkan",
    "The Blessed Madonna b2b Tiga",
    "Magdalena Bay",
    "Rico Nasty",
    "The Dare",
    "Brutalismus 3000",
    "Bob Moses",
    "Kelly Lee Owens",
    "Boy Harsher",
    "Kreayshawn",
    "Ravyn Lenae",
    "Maribou State",
    "Confidence Man",
    "Marie Davidson",
    "Chris Stussy",
    "HAAi",
    "Despacio",
    "1tbsp",
    "Arc De Soleil",
    "Bad Juuju",
    "Blawan",
    "Bolis Pupul",
    "Dabeull Live Band",
    "NEIL FRANCES",
    "Nick León",
    "Noga Erez",
    "Oppidan",
    "Prospa b2b KETTAMA",
    "salute",
    "SHEE",
    "Ski Aggu",
    "SKIIS",
    "Swimming Paul",
    "The Hellp",
    "Villager",
    "X CLUB",
    "Zack Fox",
    "Horse Meat Disco",
    "Nate Sib",
    "Jazzy",
    "KILIMANJARO",
    "Kumo 99",
    "Loukeman",
    "Yousuke Yukimatsu",
    "Haute & Freddy",
    "KI/KI",
    "Hamdi",
    "Dylan Brady",
    "MALUGI",
    "DJ Gigola",
  ],
} satisfies Festival;

// Dog Blood = Skrillex & Boys Noize.
export const portola2026 = {
  id: "portola-2026",
  name: "Portola",
  year: 2026,
  startDate: "2026-09-26",
  location: "San Francisco, CA",
  dates: "Sep 26–27",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Robyn",
    "Dog Blood",
    "Swedish House Mafia",
    "Tiësto",
    "Zara Larsson",
    "Four Tet",
    "Soulwax",
    "Fatboy Slim",
    "Skepta",
    "Parcels",
    "Tove Lo",
    "Overmono",
    "Mochakk",
    "Fcukers",
    "Mike D 5D",
    "Groove Armada",
    "DJ Shadow",
    "Tricky",
    "Bassvictim",
    "Gelli Haha",
    "Melanie C",
    "KETTAMA",
    "Prospa",
    "horsegiirL",
    "Ninajirachi",
    "underscores",
    "Kelela",
    "Daphni",
    "JT",
    "Channel Tres",
    "ear",
    "SG Lewis Live",
    "Despacio",
    "Oskar Med K",
    "Airwolf Paradise",
    "Mind Enterprises",
    "Clearcast",
    "Max Styler",
    "Beltran b2b Ben Sterling",
    "Chloé Caillet",
    "Ranger Trucco b2b Alisha",
    "Marlon Hoffstadt",
    "VTSS",
    "Brunello",
    "Silva Bumpa",
    "Dean Turnley",
    "nimino",
    "Erika b2b SF Cowboy",
    "ZULAN",
    "ADÉLA",
    "Azzecca",
    "Torren Foot",
    "Jigitz",
    "Jyoty",
    "Six Sex",
    "Nate Sib",
    "MGNA Crrrta",
    "Felly Fell",
  ],
} satisfies Festival;
