import type { Festival } from "@/lib/festivals";

const GRADIENT = "from-amber-200 via-rose-400 to-indigo-500";

// 2022–2025 source: search summaries of edm.fandom.com, festtimetable.com, djmag.com, billboard.com,
// 1001tracklists.com, ravejungle.com (pages couldn't be fetched). Mainstage is near-complete each year;
// other stages are mostly announcement highlights (~100 of 600+ artists).

export const tomorrowland2022 = {
  id: "tomorrowland-2022",
  name: "Tomorrowland",
  year: 2022,
  startDate: "2022-07-15",
  location: "Boom, Belgium",
  dates: "Jul 15–17, 22–24 & 29–31",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Martin Garrix",
    "Armin van Buuren",
    "Hardwell",
    "Dimitri Vegas & Like Mike",
    "Tiësto",
    "Charlotte de Witte",
    "Marshmello",
    "Alesso",
    "Major Lazer Soundsystem",
    "Lost Frequencies",
    "Steve Aoki",
    "Alan Walker",
    "FISHER",
    "AFROJACK b2b R3HAB",
    "AFROJACK",
    "Paul Kalkbrenner",
    "Solomun",
    "Tale Of Us",
    "Nicky Romero",
    "Oliver Heldens",
    "Timmy Trumpet",
    "W&W",
    "ALOK",
    "Kölsch",
    "Purple Disco Machine",
    "Vintage Culture",
    "MEDUZA",
    "ARTBAT",
    "Robin Schulz",
    "Martin Solveig b2b Kungs",
    "Kungs",
    "NERVO",
    "Maceo Plex",
    "Jamie Jones",
    "Reinier Zonneveld",
    "Yves Deruyter",
    "Matisse & Sadko",
    "B Jones",
    "Cat Dealers",
    "Laidback Luke",
    "Laidback Luke presents Wayback Luke",
    "Dombresky b2b Noizu",
    "Quintino",
    "Yves V",
    "Sunnery James & Ryan Marciano",
    "Chocolate Puma",
    "Joel Corry",
    "MATTN",
    "Pretty Pink",
    "Cellini",
    "Mike Williams",
    "MORTEN",
    "Seth Hills",
    "Henri PFR",
    "LP Giobbi",
    "Maxim Lany",
    "Third ≡ Party",
    "DJ Licious & Delafino",
    "DJ Licious",
    "James Hype",
    "Tinlicker",
    "Ofenbach",
    "Da Tweekaz",
    "Ape Rave Club",
    "Öwnboss",
    "Yellow Claw",
    "ACRAZE",
    "Lucas & Steve",
    "Regard",
    "3 Are Legend",
    "Comrad & Friends",
    "DJs From Mars",
    "KC Lights",
    "Tom & Collins",
    "Topic",
    "Above & Beyond",
    "Nicole Moudaber",
    "Diplo",
    "Amelie Lens",
    "Eric Prydz presents HOLO",
    "Dombresky",
    "John Summit",
    "Krewella",
    "Claptone",
    "Nico Moreno",
    "Adam Beyer",
    "ANNA",
    "Joseph Capriati",
    "Ben Klock",
    "Helena Hauff",
    "Pan-Pot",
  ],
} satisfies Festival;

export const tomorrowland2023 = {
  id: "tomorrowland-2023",
  name: "Tomorrowland",
  year: 2023,
  startDate: "2023-07-21",
  location: "Boom, Belgium",
  dates: "Jul 21–23 & 28–30",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Martin Garrix",
    "Armin van Buuren",
    "Tiësto",
    "Hardwell",
    "Dimitri Vegas & Like Mike",
    "The Chainsmokers",
    "Alesso",
    "Steve Aoki",
    "Steve Angello & Sebastian Ingrosso",
    "Steve Angello",
    "Tale Of Us",
    "Paul Kalkbrenner",
    "AFROJACK",
    "ALOK",
    "Lost Frequencies",
    "Timmy Trumpet",
    "Amelie Lens",
    "Dom Dolla",
    "Purple Disco Machine",
    "Kölsch",
    "Nina Kraviz",
    "Vintage Culture",
    "Vini Vici",
    "R3HAB b2b W&W",
    "John Newman",
    "NERVO",
    "Indira Paganotto",
    "Claptone",
    "Anfisa Letyago",
    "Andromedik",
    "Henri PFR",
    "MATTN",
    "Sunnery James & Ryan Marciano",
    "Laidback Luke presents Wayback Luke",
    "Laidback Luke",
    "220 KID",
    "Lilly Palmer",
    "Gordo",
    "James Hype",
    "Amber Broos",
    "Korolova",
    "Yves Deruyter",
    "Da Tweekaz",
    "Brina Knauss",
    "Matisse & Sadko",
    "Öwnboss",
    "B Jones",
    "Carola",
    "Goodboys",
    "Yves V & Regi",
    "Eric Prydz presents HOLO",
    "Adriatique",
    "Anyma",
    "CamelPhat",
    "Colyn",
    "Kevin de Vries",
    "Above & Beyond",
    "ANNA",
    "Honey Dijon",
    "SVDDEN DEATH",
    "Black Coffee",
    "Don Diablo",
    "Netsky",
    "Nicky Romero",
    "Oliver Heldens",
    "Robin Schulz",
    "Topic",
    "&ME",
    "Adam Beyer",
    "Agents of Time",
    "Âme",
    "Bedouin",
    "Boris Brejcha",
    "Cellini",
    "Dino Lenny",
    "Dixon",
    "DJ Tennis",
    "Joris Voorn",
    "Joseph Capriati",
    "Maceo Plex",
    "Mathame",
    "Mind Against",
    "Reinier Zonneveld",
    "Stephan Bodzin",
  ],
} satisfies Festival;

// 20-year anniversary. REZZMAU5 = REZZ b2b deadmau5.
export const tomorrowland2024 = {
  id: "tomorrowland-2024",
  name: "Tomorrowland",
  year: 2024,
  startDate: "2024-07-19",
  location: "Boom, Belgium",
  dates: "Jul 19–21 & 26–28",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Swedish House Mafia",
    "Armin van Buuren",
    "David Guetta",
    "Tiësto",
    "Hardwell",
    "REZZMAU5",
    "Dimitri Vegas & Like Mike",
    "Steve Aoki",
    "Tale Of Us",
    "Alesso",
    "Timmy Trumpet",
    "3 Are Legend",
    "Anyma",
    "AFROJACK",
    "Lost Frequencies",
    "Solomun",
    "Boris Brejcha",
    "Keinemusik",
    "ALOK",
    "Amelie Lens",
    "ANNA",
    "Adriatique",
    "Kölsch",
    "Netsky",
    "NERVO",
    "Kevin de Vries",
    "Oliver Heldens",
    "Vintage Culture",
    "John Newman",
    "Indira Paganotto",
    "Sara Landry",
    "Miss Monique",
    "Öwnboss",
    "W&W",
    "Da Tweekaz",
    "Laidback Luke presents Wayback Luke",
    "Cat Dealers",
    "Goodboys",
    "Eliza Rose",
    "Yves V",
    "MANDY",
    "Franky Rizardo",
    "Yves Deruyter",
    "Omdat Het Kan & Average Rob",
    "MATTN",
    "Antdot b2b Maz",
    "Agents of Time",
    "Henri PFR",
    "Dimension",
    "Bassjackers",
    "B Jones",
    "Rose Ringed",
    "USED",
    "MORTEN",
    "Amber Broos",
    "Sunnery James & Ryan Marciano",
    "One World Radio Soundsystem",
    "Blasterjaxx",
    "Regi b2b Mark With a K",
    "OGUZ",
    "Kapuchon",
    "Argy",
    "Chris Avantgarde",
    "MRAK",
    "Olympe",
    "The Subs",
    "Juliet Fox",
    "Bermio",
    "Andromedik",
    "Luude",
    "Grafix",
    "ACRAZE",
    "Adam Beyer",
    "Bonobo b2b Dixon",
    "Solomun b2b Four Tet",
    "Joris Voorn b2b Yotto",
    "Don Diablo",
    "Kungs",
    "MEDUZA",
    "Nicky Romero",
    "Purple Disco Machine",
    "Steve Angello",
    "The Blessed Madonna",
    "Topic",
    "Vini Vici",
  ],
} satisfies Festival;

// A fire destroyed the Mainstage two days before; a replacement stage opened on day one.
export const tomorrowland2025 = {
  id: "tomorrowland-2025",
  name: "Tomorrowland",
  year: 2025,
  startDate: "2025-07-18",
  location: "Boom, Belgium",
  dates: "Jul 18–20 & 25–27",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Martin Garrix",
    "David Guetta",
    "Swedish House Mafia",
    "Armin van Buuren",
    "Hardwell",
    "Dimitri Vegas & Like Mike",
    "Dimitri Vegas",
    "Charlotte de Witte",
    "Amelie Lens",
    "Anyma",
    "Axwell",
    "FISHER",
    "Steve Aoki",
    "ALOK",
    "Alan Walker",
    "Solomun",
    "Lost Frequencies",
    "John Summit",
    "Eric Prydz",
    "Kaskade",
    "MEDUZA",
    "ARTBAT b2b Kölsch",
    "ARTBAT",
    "ANNA",
    "NERVO",
    "Vini Vici",
    "Sub Zero Project",
    "Nicky Romero",
    "Agents of Time",
    "Odymel b2b Pegassi",
    "Mike Williams",
    "Fedde Le Grand",
    "DubVision b2b Third ≡ Party",
    "Miss Monique",
    "B Jones",
    "Cassian b2b Kevin de Vries",
    "Arielle Free b2b Sam Divine",
    "Goodboys",
    "Matroda",
    "Maddix",
    "Sub Focus",
    "MATTN",
    "Bob Sinclar b2b Paloma",
    "Merow",
    "Matisse & Sadko",
    "Andromedik",
    "MANDY",
    "Yves V",
    "Disco Dom",
    "Cyril",
    "Quintino",
    "Henri PFR",
    "Argy",
    "John Newman",
    "MORTEN",
    "Push",
    "Mr. Belt & Wezol",
    "BENNETT",
    "R3HAB",
    "Mahmut Orhan",
    "Mind Against",
    "Nico Moreno",
    "HI-LO & Eli Brown",
    "Joris Voorn & Rose Ringed",
    "Rivo",
    "Semsei",
    "Fideles",
    "Mathame",
    "AZYR & Nico Moreno",
    "EMILIJA",
    "Fantasm",
    "Faster Horses",
    "Hannah Laing",
    "Holy Priest",
    "NOVAH",
    "VIDO & BYØRN",
    "Clara Cuvé",
    "Indira Paganotto",
    "Klaps",
    "Marhu",
    "ONYVAA",
    "Patrick Mason",
    "Valentino",
    "Aaron Hibell",
    "Airod",
    "Ampe",
    "Até & Salin",
    "Funk Tribu",
    "VTSS b2b SPFDJ",
    "AFROJACK",
    "Bob Sinclar",
    "Amber Broos",
    "Job Jobse",
  ],
} satisfies Festival;

// Source: search summaries of revolution935.com, ravejungle.com, djmag.com, beatportal.com,
// clashfinder.com, trance-family.com (pages couldn't be fetched). Mainstage is near-complete;
// ~150 of 500+ artists overall.
export const tomorrowland2026 = {
  id: "tomorrowland-2026",
  name: "Tomorrowland",
  year: 2026,
  startDate: "2026-07-17",
  location: "Boom, Belgium",
  dates: "Jul 17–19 & 24–26",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Calvin Harris",
    "David Guetta",
    "Martin Garrix",
    "The Chainsmokers",
    "Armin van Buuren",
    "Hardwell",
    "Dimitri Vegas & Like Mike",
    "FISHER",
    "John Summit",
    "Alesso",
    "Steve Angello",
    "Sebastian Ingrosso",
    "AFROJACK b2b R3HAB",
    "Steve Aoki",
    "Lost Frequencies",
    "ALOK",
    "Nicky Romero",
    "Boris Brejcha",
    "Charlotte de Witte",
    "Chase & Status",
    "Sara Landry",
    "Indira Paganotto",
    "Miss Monique",
    "Kölsch",
    "Kevin de Vries",
    "Marlon Hoffstadt",
    "NERVO",
    "NOVAH",
    "Henri PFR",
    "Agents of Time",
    "Sub Zero Project",
    "Morten",
    "John Newman",
    "Vintage Culture",
    "Disco Lines",
    "Bassjackers",
    "Maddix",
    "HALŌ",
    "Merow",
    "Stephani B",
    "Omdat Het Kan & Average Rob",
    "Hannah Laing",
    "Karakals",
    "MALUGI",
    "B Jones",
    "Volkoder",
    "Ely Oaks",
    "Yves V",
    "Angemi",
    "Mike Williams",
    "D.O.D",
    "MATTN",
    "Odd Mob",
    "Cyril",
    "Lucas & Steve",
    "Alan Walker",
    "Kaskade",
    "Amelie Lens",
    "ILLENIUM",
    "REZZ",
    "Subtronics",
    "Seven Lions",
    "Sullivan King",
    "Riot Ten",
    "Liquid Stranger",
    "Brennan Heart",
    "Sasha",
    "ZHU",
    "James Hype",
    "ARTBAT",
    "Argy",
    "Massano",
    "Meduza",
    "Max Styler",
    "Holy Priest",
    "Space 92",
    "I Hate Models",
    "Nico Moreno",
    "Onlynumbers",
    "AZYR",
    "Dyen b2b Maddix",
    "BYORN b2b Shlømo",
    "Da Capo b2b Caiiro b2b Enoo Napa",
    "AWEN",
    "Danni Gato",
    "Thakzin",
    "Rosey Gold",
    "Vanco",
    "Aaron Hibell",
    "ÆON:MODE",
    "ALLEYCVT",
    "Andromedik",
    "Arcando",
    "Chris Lorenzo",
    "Dannic",
    "Dimitri Vangelis & Wyman",
    "DJ Tennis",
    "Dyzen",
    "Gorgon City",
    "Gryffin",
    "GUZ",
    "Joris Voorn",
    "Kanine",
    "Level Up",
    "Malaa",
    "Marsolo",
    "Matisse & Sadko",
    "Mesto",
    "Morgan Seatree",
    "Netsky",
    "Ranger Trucco",
    "Sick Individuals",
    "Wilkinson",
    "CVNTS",
    "KETTAMA b2b Michael Bibi",
    "Yazzmin",
    "Alison Wonderland",
    "Junkie Kid",
    "Laidback Luke",
    "Chocolate Puma",
    "Kaaze",
    "Quintino",
    "Roddy Lima",
    "Netherworld",
    "Vikkstar",
    "SHEE",
    "LP Giobbi",
    "Paris Hilton",
    "Vinne",
    "Cherry Moon Legends (& Friends)",
    "Bountyhunter",
    "Danny Corten",
    "Dimitri Cooman",
    "DJ Ghost",
    "Franky Kloeck",
    "Jamie Dill",
    "Maite Dedecker",
    "Quincy",
    "Youri Parker",
  ],
} satisfies Festival;
