import type { Festival } from "@/lib/festivals";

// Source: search summaries of revolution935.com, ravejungle.com, djmag.com, beatportal.com,
// clashfinder.com, trance-family.com (pages couldn't be fetched). Mainstage is near-complete;
// ~150 of 500+ artists overall.
export const tomorrowland2026 = {
  id: "tomorrowland-2026",
  name: "Tomorrowland",
  year: 2026,
  startDate: "2026-07-17",
  location: "Boom, Belgium",
  dates: "Jul 17–19 & 24–26",
  gradient: "from-amber-200 via-rose-400 to-indigo-500",
  partial: true,
  lineup: [
    "Calvin Harris",
    "David Guetta",
    "Martin Garrix",
    "The Chainsmokers",
    "Armin van Buuren",
    "Hardwell",
    "Dimitri Vegas & Like Mike",
    "FISHER",
    "John Summit",
    "Alesso",
    "Steve Angello",
    "Sebastian Ingrosso",
    "AFROJACK b2b R3HAB",
    "Steve Aoki",
    "Lost Frequencies",
    "ALOK",
    "Nicky Romero",
    "Boris Brejcha",
    "Charlotte de Witte",
    "Chase & Status",
    "Sara Landry",
    "Indira Paganotto",
    "Miss Monique",
    "Kölsch",
    "Kevin de Vries",
    "Marlon Hoffstadt",
    "NERVO",
    "NOVAH",
    "Henri PFR",
    "Agents of Time",
    "Sub Zero Project",
    "Morten",
    "John Newman",
    "Vintage Culture",
    "Disco Lines",
    "Bassjackers",
    "Maddix",
    "HALŌ",
    "Merow",
    "Stephani B",
    "Omdat Het Kan & Average Rob",
    "Hannah Laing",
    "Karakals",
    "MALUGI",
    "B Jones",
    "Volkoder",
    "Ely Oaks",
    "Yves V",
    "Angemi",
    "Mike Williams",
    "D.O.D",
    "MATTN",
    "Odd Mob",
    "Cyril",
    "Lucas & Steve",
    "Alan Walker",
    "Kaskade",
    "Amelie Lens",
    "ILLENIUM",
    "REZZ",
    "Subtronics",
    "Seven Lions",
    "Sullivan King",
    "Riot Ten",
    "Liquid Stranger",
    "Brennan Heart",
    "Sasha",
    "ZHU",
    "James Hype",
    "ARTBAT",
    "Argy",
    "Massano",
    "Meduza",
    "Max Styler",
    "Holy Priest",
    "Space 92",
    "I Hate Models",
    "Nico Moreno",
    "Onlynumbers",
    "AZYR",
    "Dyen b2b Maddix",
    "BYORN b2b Shlømo",
    "Da Capo b2b Caiiro b2b Enoo Napa",
    "AWEN",
    "Danni Gato",
    "Thakzin",
    "Rosey Gold",
    "Vanco",
    "Aaron Hibell",
    "ÆON:MODE",
    "ALLEYCVT",
    "Andromedik",
    "Arcando",
    "Chris Lorenzo",
    "Dannic",
    "Dimitri Vangelis & Wyman",
    "DJ Tennis",
    "Dyzen",
    "Gorgon City",
    "Gryffin",
    "GUZ",
    "Joris Voorn",
    "Kanine",
    "Level Up",
    "Malaa",
    "Marsolo",
    "Matisse & Sadko",
    "Mesto",
    "Morgan Seatree",
    "Netsky",
    "Ranger Trucco",
    "Sick Individuals",
    "Wilkinson",
    "CVNTS",
    "KETTAMA b2b Michael Bibi",
    "Yazzmin",
    "Alison Wonderland",
    "Junkie Kid",
    "Laidback Luke",
    "Chocolate Puma",
    "Kaaze",
    "Quintino",
    "Roddy Lima",
    "Netherworld",
    "Vikkstar",
    "SHEE",
    "LP Giobbi",
    "Paris Hilton",
    "Vinne",
    "Cherry Moon Legends (& Friends)",
    "Bountyhunter",
    "Danny Corten",
    "Dimitri Cooman",
    "DJ Ghost",
    "Franky Kloeck",
    "Jamie Dill",
    "Maite Dedecker",
    "Quincy",
    "Youri Parker",
  ],
} satisfies Festival;
