import type { Festival } from "@/lib/festivals";

// Source: search summaries of miaminewtimes.com, edm.com, local10.com, djmag.com set times and
// umfworldwide.com / edmidentity.com phase announcements (pages couldn't be fetched). ~150 of ~166 artists.
export const ultra2026 = {
  id: "ultra-miami-2026",
  name: "Ultra Miami",
  year: 2026,
  startDate: "2026-03-27",
  location: "Miami, FL",
  dates: "Mar 27–29",
  gradient: "from-cyan-300 via-blue-500 to-violet-600",
  partial: true,
  lineup: [
    "Swedish House Mafia",
    "Eric Prydz",
    "Carl Cox",
    "Armin van Buuren",
    "Martin Garrix b2b Alesso",
    "John Summit",
    "DJ Snake",
    "Major Lazer",
    "Hardwell",
    "ILLENIUM",
    "Sebastian Ingrosso b2b Steve Angello",
    "Adam Beyer b2b Joseph Capriati",
    "Amelie Lens b2b Sara Landry",
    "Adriatique",
    "Excision",
    "AFROJACK",
    "Steve Aoki",
    "Alan Walker",
    "Boris Brejcha",
    "Vintage Culture",
    "The Martinez Brothers",
    "BZRP",
    "ZHU",
    "Madeon",
    "Boys Noize",
    "Louis The Child",
    "ISOxo",
    "ARTBAT",
    "Nicky Romero",
    "Loud Luxury",
    "R3HAB",
    "Marlon Hoffstadt",
    "Armin van Buuren b2b Marlon Hoffstadt",
    "Sara Landry",
    "Miss Monique",
    "Eli Brown",
    "Sasha & John Digweed",
    "Deep Dish",
    "Argy b2b Mind Against",
    "Dennis Cruz b2b Seth Troxler",
    "Joris Voorn b2b Korolova",
    "Colyn b2b Innellea",
    "Cassian",
    "Clara Cuvé",
    "Clara Cuvé b2b Shlømo",
    "Massano",
    "Mar-T",
    "Scenarios",
    "Bassett b2b Christopher James",
    "Godtripper",
    "Alt8",
    "999999999",
    "JOA",
    "Olympe",
    "Rivo",
    "Kasia",
    "m.O.N.R.O.E.",
    "Plastik Funk",
    "Black Fancy",
    "Malóne",
    "Rossi.",
    "Alan Fitzpatrick b2b Marco Faraone",
    "Juliet Fox",
    "Frank Walker",
    "VOYD",
    "WORSHIP",
    "Gil Glaze",
    "Mykris",
    "HALŌ",
    "Maddix",
    "Kapuchon",
    "Me N Ü",
    "Vini Vici",
    "Lilly Palmer",
    "SUPERSTRINGS",
    "Matty Ralph",
    "Prada2000",
    "Julian Cross",
    "Distinct Motive",
    "Sidequest",
    "Daniel Allan",
    "ARMNHMR",
    "HOL!",
    "Bou",
    "Kai Wachi",
    "Outlaw b2b Trym",
    "Hamdi",
    "¥ØU$UK€ ¥UK1MAT$U",
    "Big Florida",
    "GorillaT",
    "BOLO",
    "LAYZ",
    "Andy C",
    "Holy Priest",
    "PEEKABOO",
    "Ray Volpe b2b Sullivan King",
    "WANKDAT (Crankdat b2b Wooli)",
    "Levity presents Lasership",
    "Of The Trees",
    "Black Tiger Sex Machine presents Connected Fighters",
    "Shima",
    "Afrobeta",
    "Brutalismus 3000",
    "Snow Strippers",
    "Confidence Man",
    "Miss Bashful",
    "TIMELESS (Deorro, Mike Posner & MORTEN)",
    "Parisi",
    "Boiish",
    "The Bloody Beetroots",
    "Laidback Luke",
    "Riot Ten",
    "Jessica Audiffred",
    "Nostalgix",
    "Ookay",
    "Linney",
    "Kreation",
    "Darksiderz",
    "Audiofreq",
    "The Purge",
    "The Saints",
    "Coone",
    "Da Tweekaz",
    "Mish",
    "Dual Damage",
    "D-Sturb",
    "Soren",
    "Peterblue",
    "DJ Gigola",
    "MCR-T",
    "Fcukers",
    "X CLUB",
    "Frost Children",
    "Eera",
    "Armand Van Helden",
    "Kelly Lee Owens",
    "MPH",
  ],
} satisfies Festival;
