import type { Festival } from "@/lib/festivals";

const GRADIENT = "from-cyan-300 via-blue-500 to-violet-600";

// 2022–2025 source: search summaries of billboard.com, edm.com, edmidentity.com, miaminewtimes.com,
// themiamiguide.com, edmtunes.com (pages couldn't be fetched). Surprise guest appearances during
// other artists' sets aren't listed.

export const ultra2022 = {
  id: "ultra-miami-2022",
  name: "Ultra Miami",
  year: 2022,
  startDate: "2022-03-25",
  location: "Miami, FL",
  dates: "Mar 25–27",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Kygo",
    "ILLENIUM",
    "Hardwell",
    "Martin Garrix",
    "David Guetta",
    "Tiësto",
    "Armin van Buuren",
    "Carl Cox (Hybrid Live)",
    "Swedish House Mafia",
    "AFROJACK",
    "Alesso",
    "DJ Snake",
    "FISHER",
    "Zeds Dead",
    "Knife Party",
    "Seven Lions",
    "Adam Beyer",
    "Amelie Lens",
    "Nina Kraviz",
    "Tale Of Us",
    "Sasha & John Digweed",
    "Joseph Capriati",
    "Boris Brejcha",
    "CamelPhat",
    "Vintage Culture b2b Claptone",
    "Jauz b2b NGHTMRE",
    "Armin van Buuren b2b Reinier Zonneveld",
    "Pendulum (Live)",
    "Alison Wonderland",
    "SVDDEN DEATH presents VOYD",
    "Madeon (Live)",
    "SOFI TUKKER (Live)",
    "Oliver Tree (Live)",
    "Gareth Emery (Analog Live)",
    "SLANDER",
    "KSHMR (The Live Experience)",
    "Oliver Heldens",
    "Timmy Trumpet",
    "Nicky Romero",
    "Tchami",
    "Vini Vici",
    "ACRAZE",
    "Cedric Gervais",
    "Jeffrey Sutorius",
    "Sam Feldt",
    "Mykris",
    "Tommie Sunshine",
    "Frank Walker",
    "Sullivan King (Live)",
    "Ookay (Live)",
    "Elohim (Live)",
    "Forester",
    "Olan",
    "Afrobeta",
    "Black Tiger Sex Machine",
    "Whethan",
    "4B b2b SAYMYNAME",
    "Slushii",
    "Wax Motif",
    "Mija b2b GG Magree",
    "A Hundred Drums",
    "Ares Carter",
    "Ghost Rydr (Joyryde b2b Ghastly)",
    "Kill The Noise",
    "Krewella",
    "Whipped Cream",
    "Roni Size",
    "Hybrid Minds",
    "Raiden",
    "Metaphysical",
    "Justin Mylo",
    "Julian Jordan",
    "DubVision",
    "Matisse & Sadko",
    "KVSH b2b Pontifexx",
    "Florian Picasso",
    "Matt Nash",
    "Osrin",
    "Infuze",
    "FrostTop",
    "Kraysh",
    "Leotrix",
    "NITEPUNK",
    "PEEKABOO",
    "RIOT",
    "Saka",
    "Space Laces",
    "Wavedash",
    "William Black",
    "Coone",
    "Gammer",
    "Da Tweekaz",
    "Sub Zero Project",
    "Ben Nicky presents Xtreme",
    "Darren Styles",
    "Audiofreq",
    "Lil Texas",
    "Darksiderz",
    "Pulsatorz",
    "ANNA",
    "Dubfire",
    "Michael Bibi",
    "Anfisa Letyago",
    "Giorgia Angiuli (Live)",
    "Brennen Grey",
    "Reinier Zonneveld (Live)",
    "Hannes Bieger (Live)",
    "Christopher Coe (Live)",
    "Elio Riso",
    "Solardo",
    "Nic Fanciulli",
    "Dom Dolla",
    "John Summit",
    "Christian Smith b2b Cristian Varela",
    "Rafa Barrios",
    "Nala",
    "Pan-Pot",
    "Sama' Abdulhadi",
    "Ilario Alicante",
    "Matador",
    "Technasia b3b Hector b3b Carlo Lio",
    "Popof",
    "Andy Pate b2b Rod B",
    "Ann Clue",
    "Moritz Hofbauer (Live)",
    "Deniz Bul",
  ],
} satisfies Festival;

export const ultra2023 = {
  id: "ultra-miami-2023",
  name: "Ultra Miami",
  year: 2023,
  startDate: "2023-03-24",
  location: "Miami, FL",
  dates: "Mar 24–26",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Swedish House Mafia",
    "Martin Garrix",
    "Marshmello",
    "Eric Prydz presents HOLO",
    "Carl Cox",
    "Armin van Buuren",
    "Tiësto",
    "David Guetta",
    "Hardwell",
    "Zedd",
    "Alesso",
    "AFROJACK",
    "Charlotte de Witte",
    "Adam Beyer ◻︎ Cirez D",
    "Tale Of Us",
    "Kx5",
    "CamelPhat",
    "Michael Bibi",
    "Stephan Bodzin (Live)",
    "M.I.A.",
    "Grimes",
    "REZZ",
    "Subtronics",
    "Ganja White Night",
    "Gareth Emery",
    "Vini Vici",
    "Gryffin",
    "Timmy Trumpet",
    "Claude VonStroke",
    "Dom Dolla b2b Vintage Culture",
    "Oliver Heldens b2b Tchami",
    "Sam Feldt b2b Jonas Blue",
    "Maceo Plex b2b Michael Bibi",
    "Dubfire b2b Kölsch",
    "Nicole Moudaber b2b Chris Liebing",
    "HI-LO b2b TESTPILOT",
    "Armin van Buuren b2b Ferry Corsten",
    "Jauz b2b SVDDEN DEATH",
    "Gigantic NGHTMRE",
    "Liquid Stranger",
    "Kayzo (Live)",
    "Dabin",
    "CloZee",
    "Black Tiger Sex Machine presents Portals",
    "Kasablanca (Live)",
    "Becky Hill",
    "JVNA",
    "Fairlane",
    "Nicky Romero",
    "Fedde Le Grand",
    "Deorro",
    "Cedric Gervais",
    "Frank Walker",
    "Mykris",
    "Syn Cole",
    "Kapuchon",
    "Joris Voorn",
    "Anfisa Letyago",
    "Ida Engberg",
    "Maya Jane Coles",
    "Popof",
    "Space 92",
    "Enrico Sangiuliano",
    "Ilario Alicante",
    "Mathame",
    "Brennen Grey",
    "Walker & Royce",
    "VNSSA",
    "Shiba San",
    "Kyle Kinch",
    "Coone",
    "DubVision",
    "Boiish",
  ],
} satisfies Festival;

export const ultra2024 = {
  id: "ultra-miami-2024",
  name: "Ultra Miami",
  year: 2024,
  startDate: "2024-03-22",
  location: "Miami, FL",
  dates: "Mar 22–24",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Calvin Harris",
    "Peggy Gou",
    "Eric Prydz",
    "Amelie Lens",
    "FISHER x Chris Lake present UNDER CONSTRUCTION",
    "David Guetta",
    "Martin Garrix",
    "Tiësto",
    "Hardwell",
    "Armin van Buuren",
    "AFROJACK",
    "Alan Walker",
    "Excision",
    "Zeds Dead",
    "SLANDER",
    "SVDDEN DEATH",
    "Vintage Culture",
    "Nora En Pure",
    "Oliver Heldens",
    "Gryffin",
    "KSHMR",
    "Steve Aoki",
    "Seven Lions",
    "Chase & Status",
    "Elderbrook",
    "Klangkuenstler",
    "RL Grime b2b Knock2",
    "Madeon b2b San Holo",
    "Armin van Buuren b2b Oliver Heldens",
    "Black Tiger Sex Machine presents The Anime Show",
    "Adam Beyer",
    "Adriatique",
    "Sasha & John Digweed",
    "CamelPhat",
    "Nina Kraviz",
    "Reinier Zonneveld (Live)",
    "Dubfire b2b Ilario Alicante",
    "Joris Voorn b2b Kölsch",
    "HI-LO b2b Eli Brown",
    "Massano b2b Chris Avantgarde",
    "Argy",
    "ARTBAT",
    "Giorgia Angiuli (Live)",
    "LP Giobbi",
    "Mahmut Orhan",
    "Mathame (A/V Show)",
    "Mind Against",
    "Miss Monique",
    "Pan-Pot",
    "Patrick Mason",
    "Wade",
    "Ann Clue",
    "Bruno Furlan",
    "HoneyLuv",
    "Kasia",
    "MAGA",
    "Magdalena",
    "Moritz Hofbauer",
    "Rafa Barrios",
    "Victor Ruiz",
    "wAFF b2b Cuartero",
    "Andy C",
    "Orbital",
    "Sub Focus",
    "Nicky Romero",
    "Dimension",
    "Eli & Fur",
    "Apashe",
    "Disco Lines",
    "Ben Nicky",
    "Godlands",
    "Blanke",
    "Bou",
    "Jason Ross",
    "Mersiv",
    "Nostalgix",
    "Maddy O'Neal",
    "Radical Redemption",
    "Tape B",
    "Kasablanca",
    "Gem & Tauri",
    "Sound Rush",
    "Deorro",
    "Frank Walker",
    "Mykris",
    "EDX",
    "Maddix",
    "Giuseppe Ottaviani",
    "Laura van Dam",
    "Kill Safari",
    "Space Laces",
    "Wooli",
    "Eelke Kleijn",
    "Township Rebellion",
    "Chris Luno",
    "Nightlapse",
    "Ovadia",
    "Far Out",
    "Pauline Herr",
    "Trivecta",
    "Bloom Twins",
    "Gil Glaze",
    "Hartshorn",
    "KAMI",
    "Paradoks b2b Volaris",
    "Sickick",
    "3LAU",
    "Afrobeta",
    "Jai Wolf",
  ],
} satisfies Festival;

// 25th anniversary. Kaskade played a surprise set.
export const ultra2025 = {
  id: "ultra-miami-2025",
  name: "Ultra Miami",
  year: 2025,
  startDate: "2025-03-28",
  location: "Miami, FL",
  dates: "Mar 28–30",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Martin Garrix",
    "Hardwell",
    "Everything Always (Dom Dolla b2b John Summit)",
    "Skrillex",
    "Anyma b2b Solomun",
    "Axwell",
    "Carl Cox",
    "Armin van Buuren",
    "Tiësto",
    "AFROJACK",
    "Alesso",
    "Zedd",
    "Above & Beyond",
    "Gesaffelstein",
    "deadmau5 b2b Pendulum",
    "deadmau5 (retro5pective)",
    "Charlotte de Witte",
    "Adam Beyer",
    "Richie Hawtin (DEX EFX X0X)",
    "Dubfire (EVOLV)",
    "Solomun",
    "Four Tet",
    "Mau P",
    "Zeds Dead",
    "Pendulum (Live)",
    "Chase & Status",
    "Nero",
    "Knife Party",
    "Subtronics",
    "Kaskade",
    "Oliver Heldens",
    "Steve Aoki",
    "Timmy Trumpet",
    "Gryffin",
    "KSHMR (The Live Experience)",
    "LSZEE (LSDREAM + CloZee)",
    "NGHTMRE b2b Sullivan King",
    "ARTBAT",
    "Boris Brejcha",
    "999999999",
    "I Hate Models",
    "Eli Brown",
    "Miss Monique",
    "Nico Moreno",
    "Stephan Bodzin",
    "Joris Voorn (Live)",
    "Marc Romboy",
    "Carl Cox b2b Christopher Coe",
    "Chloé Caillet",
    "Kevin de Vries",
    "Josh Wink",
    "Joyhauser",
    "Nic Fanciulli",
    "Patrick Topping",
    "Korolova",
    "Moritz Hofbauer",
    "MAGA",
    "Nusha",
    "Charlie Sparks",
    "Juliet Fox",
    "Kasia",
    "Olympe",
    "Marco Faraone",
    "Mar-T",
    "Sonny Fodera",
    "Joel Corry",
    "Ruben de Ronde",
    "JEV",
    "Odd Mob",
    "MORTEN",
    "Sam Feldt",
    "Frank Walker",
    "Kapuchon",
    "Gil Glaze",
    "Mykris",
    "TOKiMONSTA",
    "Said The Sky",
    "PEEKABOO",
    "Barclay Crenshaw",
    "Becky Hill",
    "Boiish (Live)",
    "Infected Mushroom",
    "Afrobeta",
    "Modestep",
    "Skepsis",
    "ATLiens",
    "Hedex",
    "Crankdat",
    "Marauda",
    "Wilkinson",
    "LTJ Bukem",
    "Level Up",
    "Dillon Nathaniel",
  ],
} satisfies Festival;

// Source: search summaries of miaminewtimes.com, edm.com, local10.com, djmag.com set times and
// umfworldwide.com / edmidentity.com phase announcements (pages couldn't be fetched). ~150 of ~166 artists.
export const ultra2026 = {
  id: "ultra-miami-2026",
  name: "Ultra Miami",
  year: 2026,
  startDate: "2026-03-27",
  location: "Miami, FL",
  dates: "Mar 27–29",
  gradient: GRADIENT,
  partial: true,
  lineup: [
    "Swedish House Mafia",
    "Eric Prydz",
    "Carl Cox",
    "Armin van Buuren",
    "Martin Garrix b2b Alesso",
    "John Summit",
    "DJ Snake",
    "Major Lazer",
    "Hardwell",
    "ILLENIUM",
    "Sebastian Ingrosso b2b Steve Angello",
    "Adam Beyer b2b Joseph Capriati",
    "Amelie Lens b2b Sara Landry",
    "Adriatique",
    "Excision",
    "AFROJACK",
    "Steve Aoki",
    "Alan Walker",
    "Boris Brejcha",
    "Vintage Culture",
    "The Martinez Brothers",
    "BZRP",
    "ZHU",
    "Madeon",
    "Boys Noize",
    "Louis The Child",
    "ISOxo",
    "ARTBAT",
    "Nicky Romero",
    "Loud Luxury",
    "R3HAB",
    "Marlon Hoffstadt",
    "Armin van Buuren b2b Marlon Hoffstadt",
    "Sara Landry",
    "Miss Monique",
    "Eli Brown",
    "Sasha & John Digweed",
    "Deep Dish",
    "Argy b2b Mind Against",
    "Dennis Cruz b2b Seth Troxler",
    "Joris Voorn b2b Korolova",
    "Colyn b2b Innellea",
    "Cassian",
    "Clara Cuvé",
    "Clara Cuvé b2b Shlømo",
    "Massano",
    "Mar-T",
    "Scenarios",
    "Bassett b2b Christopher James",
    "Godtripper",
    "Alt8",
    "999999999",
    "JOA",
    "Olympe",
    "Rivo",
    "Kasia",
    "m.O.N.R.O.E.",
    "Plastik Funk",
    "Black Fancy",
    "Malóne",
    "Rossi.",
    "Alan Fitzpatrick b2b Marco Faraone",
    "Juliet Fox",
    "Frank Walker",
    "VOYD",
    "WORSHIP",
    "Gil Glaze",
    "Mykris",
    "HALŌ",
    "Maddix",
    "Kapuchon",
    "Me N Ü",
    "Vini Vici",
    "Lilly Palmer",
    "SUPERSTRINGS",
    "Matty Ralph",
    "Prada2000",
    "Julian Cross",
    "Distinct Motive",
    "Sidequest",
    "Daniel Allan",
    "ARMNHMR",
    "HOL!",
    "Bou",
    "Kai Wachi",
    "Outlaw b2b Trym",
    "Hamdi",
    "¥ØU$UK€ ¥UK1MAT$U",
    "Big Florida",
    "GorillaT",
    "BOLO",
    "LAYZ",
    "Andy C",
    "Holy Priest",
    "PEEKABOO",
    "Ray Volpe b2b Sullivan King",
    "WANKDAT (Crankdat b2b Wooli)",
    "Levity presents Lasership",
    "Of The Trees",
    "Black Tiger Sex Machine presents Connected Fighters",
    "Shima",
    "Afrobeta",
    "Brutalismus 3000",
    "Snow Strippers",
    "Confidence Man",
    "Miss Bashful",
    "TIMELESS (Deorro, Mike Posner & MORTEN)",
    "Parisi",
    "Boiish",
    "The Bloody Beetroots",
    "Laidback Luke",
    "Riot Ten",
    "Jessica Audiffred",
    "Nostalgix",
    "Ookay",
    "Linney",
    "Kreation",
    "Darksiderz",
    "Audiofreq",
    "The Purge",
    "The Saints",
    "Coone",
    "Da Tweekaz",
    "Mish",
    "Dual Damage",
    "D-Sturb",
    "Soren",
    "Peterblue",
    "DJ Gigola",
    "MCR-T",
    "Fcukers",
    "X CLUB",
    "Frost Children",
    "Eera",
    "Armand Van Helden",
    "Kelly Lee Owens",
    "MPH",
  ],
} satisfies Festival;
