import type { Festival } from "@/lib/festivals";

// 2022 & 2024 source: search summaries of jambase.com, musicfestivalwizard.com, edmidentity.com
// (pages couldn't be fetched). Both at Bill Graham Civic Auditorium. No SF edition in 2023.

export const wobbleland2022 = {
  id: "wobbleland-2022",
  name: "Wobbleland",
  year: 2022,
  startDate: "2022-01-14",
  location: "San Francisco, CA",
  dates: "Jan 14–16",
  gradient: "from-lime-300 via-green-500 to-emerald-700",
  partial: true,
  lineup: [
    "NGHTMRE",
    "Kayzo",
    "Ghost Rydr",
    "12th Planet",
    "Getter b2b Eptic",
    "Slushii",
    "Minnesota",
    "Riot Ten",
    "Spag Heddy",
    "Smoakland",
    "Wavedash",
    "Champagne Drip",
    "Jalaya",
    "Ravenscoon",
    "Secret Recipe",
    "Tsuruda",
    "Ternion Sound",
    "Blunts & Blondes",
    "Dirt Monkey",
    "Gammer",
    "HVDES",
    "One True God",
    "Ace Aura",
    "Decimate",
    "Jessica Audiffred",
    "Lil Texas",
    "SubDocta",
    "Zia",
    "Abelation",
    "Calcium",
    "Louder Space",
    "Midnight Tyrannosaurus",
    "Point.Blank",
    "ARIUS",
    "John Beaver",
    "Kumarion",
    "OG Nixin",
    "Slang Dogs",
    "Volt",
  ],
} satisfies Festival;

export const wobbleland2024 = {
  id: "wobbleland-2024",
  name: "Wobbleland",
  year: 2024,
  startDate: "2024-01-19",
  location: "San Francisco, CA",
  dates: "Jan 19–20",
  gradient: "from-lime-300 via-green-500 to-emerald-700",
  partial: true,
  lineup: [
    "SVDDEN DEATH",
    "Black Tiger Sex Machine presents Portals",
    "Adventure Club",
    "Kai Wachi",
    "Crankdat b2b Kompany",
    "HOL!",
    "INFEKT",
    "LAYZ",
    "Lil Texas",
    "ARTIX!",
    "Hamro",
    "Ruvlo",
    "Space Wizard",
    "Vastive",
    "Versa",
    "Zeke Beats",
    "Jalaya",
    "XHALE GHOST",
    "HE$H",
    "Jessica Audiffred",
    "Abelation",
    "Antagonizer (Away b2b Crywolf)",
    "Automhate",
    "Cyclops",
    "Emorfik",
    "Point.Blank",
    "RZRKT",
    "Shiverz",
    "Rankz",
    "Secret Recipe",
  ],
} satisfies Festival;

// Source: search summaries of edmidentity.com, bassrush.com, insomniac.com lineup pages
// (the pages themselves couldn't be fetched). "DØMINA b2b Yosuf" and "Akirah" are less certain.
export const wobbleland2026 = {
  id: "wobbleland-2026",
  name: "Wobbleland",
  year: 2026,
  startDate: "2026-08-21",
  location: "San Jose, CA",
  dates: "Aug 21–22",
  gradient: "from-lime-300 via-green-500 to-emerald-700",
  partial: true,
  lineup: [
    "Excision",
    "DJ Diesel",
    "Alison Wonderland b2b NGHTMRE",
    "Ray Volpe",
    "Adventure Club",
    "Whethan",
    "Lil Texas",
    "THE RESISTANCE",
    "DØMINA b2b Yosuf",
    "Alyssa Jolee",
    "ANOLUXX",
    "Hedex",
    "GHENGAR",
    "JSTJR",
    "Akirah",
  ],
} satisfies Festival;

// Source: search summaries of edmidentity.com, bassrush.com, jambase.com, grooveist.com
// (pages couldn't be fetched). Believed complete (~32 sets).
export const wobbleland2025 = {
  id: "wobbleland-2025",
  name: "Wobbleland",
  year: 2025,
  startDate: "2025-07-11",
  location: "Daly City, CA",
  dates: "Jul 11–12",
  gradient: "from-lime-300 via-green-500 to-emerald-700",
  lineup: [
    "Wooli",
    "Skull Machine",
    "Crankdat",
    "ATLiens",
    "Virtual Riot b2b INFEKT",
    "Ray Volpe",
    "Black Tiger Sex Machine",
    "Kai Wachi",
    "Barely Alive",
    "JEANIE b2b VAMPA presents Witching Hour",
    "Midnight Tyrannosaurus",
    "Sanzu",
    "Trivecta",
    "MUZZ",
    "Xotix",
    "Reaper",
    "HOL!",
    "SABAI",
    "Fairlane",
    "Abelation",
    "Capochino",
    "HEYZ",
    "LAYZ",
    "One True God",
    "ÆON:MODE",
    "THE RESISTANCE",
    "Majed",
    "Skellytn",
    "YDG",
    "Yosuf",
  ],
} satisfies Festival;
