import type { Festival } from "@/lib/festivals";

// Source: search summaries of edmidentity.com, bassrush.com, insomniac.com lineup pages
// (the pages themselves couldn't be fetched). "DØMINA b2b Yosuf" and "Akirah" are less certain.
export const wobbleland2026 = {
  id: "wobbleland-2026",
  name: "Wobbleland",
  year: 2026,
  startDate: "2026-08-21",
  location: "San Jose, CA",
  dates: "Aug 21–22",
  gradient: "from-lime-300 via-green-500 to-emerald-700",
  partial: true,
  lineup: [
    "Excision",
    "DJ Diesel",
    "Alison Wonderland b2b NGHTMRE",
    "Ray Volpe",
    "Adventure Club",
    "Whethan",
    "Lil Texas",
    "THE RESISTANCE",
    "DØMINA b2b Yosuf",
    "Alyssa Jolee",
    "ANOLUXX",
    "Hedex",
    "GHENGAR",
    "JSTJR",
    "Akirah",
  ],
} satisfies Festival;

// Source: search summaries of edmidentity.com, bassrush.com, jambase.com, grooveist.com
// (pages couldn't be fetched). Believed complete (~32 sets).
export const wobbleland2025 = {
  id: "wobbleland-2025",
  name: "Wobbleland",
  year: 2025,
  startDate: "2025-07-11",
  location: "Daly City, CA",
  dates: "Jul 11–12",
  gradient: "from-lime-300 via-green-500 to-emerald-700",
  lineup: [
    "Wooli",
    "Skull Machine",
    "Crankdat",
    "ATLiens",
    "Virtual Riot b2b INFEKT",
    "Ray Volpe",
    "Black Tiger Sex Machine",
    "Kai Wachi",
    "Barely Alive",
    "JEANIE b2b VAMPA presents Witching Hour",
    "Midnight Tyrannosaurus",
    "Sanzu",
    "Trivecta",
    "MUZZ",
    "Xotix",
    "Reaper",
    "HOL!",
    "SABAI",
    "Fairlane",
    "Abelation",
    "Capochino",
    "HEYZ",
    "LAYZ",
    "One True God",
    "ÆON:MODE",
    "THE RESISTANCE",
    "Majed",
    "Skellytn",
    "YDG",
    "Yosuf",
  ],
} satisfies Festival;
